/*
CREATE MULTISET TABLE UNICA_TEMP.DE_FAMILY_MEN_RALLY_STG ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      PRIMARY_USER_ID DECIMAL(18,0) NOT NULL,
      DEMO_USER_ID DECIMAL(18,0) NOT NULL,    
      SEGM_ID INTEGER NOT NULL,
	  AUD_ID INTEGER NOT NULL,
      USER_SITE_ID DECIMAL(4,0) NOT NULL,
	  TC VARCHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      RALLY_FLAG VARCHAR(25) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      POINTS VARCHAR(25) CHARACTER SET LATIN NOT CASESPECIFIC,
      PULL_DATE VARCHAR(35) CHARACTER SET LATIN NOT CASESPECIFIC,
      EXCLUDE_REASON_CD SMALLINT)
PRIMARY INDEX ( PRIMARY_USER_ID ,SEGM_ID);
*/
--drop table UNICA_TEMP.DE_FAMILY_MEN_RALLY_STG
DELETE FROM UNICA_TEMP.DE_FAMILY_MEN_RALLY_STG ALL
;


INSERT INTO UNICA_TEMP.DE_FAMILY_MEN_RALLY_STG

SELECT
	PII.PRMRY_USER_ID as PRIMARY_USER_ID,
	PII.DEMO_USER_ID,
	SEG.SEGM_ID,
	AUD.AUD_ID,
	PII.USER_SITE_ID,
	'T' as TC,
	RALLY_FLAG,
	POINTS,
	PULL_DATE ,
	NULL AS EXCLUDE_REASON_CD
FROM
P_DBM_INPUT_T.de_family_men_rally_prod RALLY
INNER JOIN PRS_SECURE_V.MDM_USER_PII AS PII on RALLY.USER_ID=PII.USER_ID
INNER JOIN	UNICA_TEMP.XMP_AUDIENCE AS AUD
			ON	AUD.AUD_NAME = 'DE_FAMILY_MEN_RALLY' AND
					77 = AUD.SITE_ID AND
					CURRENT_DATE BETWEEN AUD.START_DATE AND AUD.END_DATE
		
		INNER JOIN	UNICA_TEMP.XMP_SEGMENT AS SEG
			ON	SEG.AUD_ID = AUD.AUD_ID AND
					SEG.SEGM_NAME IN ('FAMILY_MEN_RALLY') AND
					CURRENT_DATE BETWEEN SEG.START_DATE AND SEG.END_DATE
--where PII.user_id not in (select user_id from P_DBM_INPUT_T.DE_FM_RALLY_TABLE_MAM RALLY) --seeds	for the 1st send out				
where PII.user_id not in (
176722949,
107493393,
199175982,
17676934,
845063476,
1229084683,
182212748,
114846791,
1157692775,
35929600,
927684273,
104517236,
1187848288,
165374832,
175863163,
51655605,
1057854418,
69588776,
178073211,
88617290,
287673190,
36413308,
696782356,
1115585042,
431019864,
67388821,
129084172,
118365892,
613669529
)  -- 29 users from blacklist
GROUP BY 1,2,3,4,5,6,7,8,9,10
					;
					
					INSERT INTO UNICA_TEMP.DE_FAMILY_MEN_RALLY_STG

SELECT
	PII.PRMRY_USER_ID as PRIMARY_USER_ID,
	PII.DEMO_USER_ID,
	SEG.SEGM_ID,
	AUD.AUD_ID,
	PII.USER_SITE_ID,
	'T' as TC,
	RALLY_FLAG,
	POINTS,
	PULL_DATE ,
	NULL AS EXCLUDE_REASON_CD
FROM
P_DBM_INPUT_T.DE_FM_RALLY_TABLE_MAM RALLY --seeds
INNER JOIN PRS_SECURE_V.MDM_USER_PII AS PII on RALLY.USER_ID=PII.USER_ID
INNER JOIN UNICA_TEMP.XMP_AUDIENCE AS AUD
			ON	AUD.AUD_NAME = 'DE_FAMILY_MEN_RALLY' AND
					77 = AUD.SITE_ID AND
					CURRENT_DATE BETWEEN AUD.START_DATE AND AUD.END_DATE
		
		INNER JOIN	 UNICA_TEMP.XMP_SEGMENT AS SEG
			ON	SEG.AUD_ID = AUD.AUD_ID AND
					SEG.SEGM_NAME IN ('FAMILY_MEN_RALLY_SEED') AND
					CURRENT_DATE BETWEEN SEG.START_DATE AND SEG.END_DATE
					where demo_user_id= '1615914537'
GROUP BY 1,2,3,4,5,6,7,8,9,10
					;
					
		--	sel * from UNICA_TEMP.DE_FAMILY_MEN_RALLY_STG;
	/*************************************************************************************************
* STANDARD SUPPRESSIONS, WATERFALL
**************************************************************************************************/

--USER SITE
UPDATE A 
FROM UNICA_TEMP.DE_FAMILY_MEN_RALLY_STG AS A
SET EXCLUDE_REASON_CD =  5
WHERE 	EXCLUDE_REASON_CD IS NULL AND
			EXISTS	(
						SELECT *
						FROM PRS_SECURE_V.MDM_USER_PII AS PII
						WHERE
							A.DEMO_USER_ID = PII.USER_ID AND
							PII.USER_SITE_ID <> 77 AND
							 user_slctd_id not in (
'mogucan',  --Gybasova, Kristina
'marieck_6',  --Eckert, Thomas
'sraudschus', --Peijan, Stefanie
'emnewman', --Newman, Emma
'mllewiwa', --(Kristin Wyrwa)
'the9280', -- (Theresa Thüs)
'sa-32439' , --(Sandy Kim)
'kathihartung832',
'marekmk', 
'dmalhao@ebay.com',
'psperling@ebay.de',  
'steffisoleil84')
						)
;

--NON-CONFIRMED USERS
UPDATE A 
FROM UNICA_TEMP.DE_FAMILY_MEN_RALLY_STG AS A
SET EXCLUDE_REASON_CD =  10
WHERE 	EXCLUDE_REASON_CD IS NULL AND
			EXISTS	(
						SELECT *
						FROM PRS_SECURE_V.MDM_USER_PII AS PII
						WHERE
							A.DEMO_USER_ID = PII.USER_ID AND
							PII.CNFRMD_YN = 'N'
						)
;

--GXO
UPDATE A 
FROM UNICA_TEMP.DE_FAMILY_MEN_RALLY_STG AS A
SET EXCLUDE_REASON_CD =  15
WHERE 	EXCLUDE_REASON_CD IS NULL AND
			EXISTS	(
						SELECT *
						FROM PRS_SECURE_V.MDM_USER_PII AS PII
						WHERE 
							A.DEMO_USER_ID = PII.USER_ID AND
							PII.RGSTRD_YN = 'N'
						)
;

--BAD FEEDBACK
UPDATE A 
FROM UNICA_TEMP.DE_FAMILY_MEN_RALLY_STG AS A
SET EXCLUDE_REASON_CD =  20
WHERE 	EXCLUDE_REASON_CD IS NULL AND
			EXISTS	(
						SELECT *
						FROM PRS_SECURE_V.MDM_USER_PII AS PII
						WHERE 
							A.DEMO_USER_ID = PII.USER_ID AND
							PII.FDBCK_YN = 'N'
						)
;

--CRM_GH FLAG
UPDATE A 
FROM UNICA_TEMP.DE_FAMILY_MEN_RALLY_STG AS A
SET EXCLUDE_REASON_CD =  25
WHERE 	EXCLUDE_REASON_CD IS NULL AND
			EXISTS	(
						SELECT *
						FROM PRS_SECURE_V.MDM_USER_PII AS PII
						WHERE
							A.DEMO_USER_ID = PII.USER_ID AND
							PII.CRM_GH_YN = 'Y'
						)
;

--B2C
UPDATE A 
FROM UNICA_TEMP.DE_FAMILY_MEN_RALLY_STG AS A
SET EXCLUDE_REASON_CD =  30
WHERE 	EXCLUDE_REASON_CD IS NULL AND
			EXISTS	(
						SELECT *
						FROM PRS_SECURE_V.MDM_USER_PII AS PII
						WHERE
							A.DEMO_USER_ID = PII.USER_ID AND
							PII.B2C_SLR_YN = 'Y'
						)
;			

--RISK
UPDATE A 
FROM UNICA_TEMP.DE_FAMILY_MEN_RALLY_STG AS A
SET EXCLUDE_REASON_CD =  35
WHERE 	EXCLUDE_REASON_CD IS NULL AND
			EXISTS	(
						SELECT *
                        FROM access_views.dw_user_issue PII
						WHERE A.DEMO_USER_ID = PII.USER_ID AND
						scenario_id IN (1, 248, 250, 265, 491, 534, 535, 566, 629)
						AND status_id = 0		
						)
;



/*************************************************************************************************
MESSAGE LEVEL - START WITH HERO MESSAGES
Taking data from Audience, populating message staging table
***************************************************************************************************/

DELETE FROM UNICA_TEMP.DE_FM_RALLY_MESSAGE_STG ALL
;

INSERT INTO UNICA_TEMP.DE_FM_RALLY_MESSAGE_STG
SELECT
      AUD.PRIMARY_USER_ID,
      AUD.DEMO_USER_ID,    
	AUD.AUD_ID,
	AUD.SEGM_ID,
	MSG.MSG_ID,
	NULL as JOURNEY_ID,
	NULL as SEQUENCE,	
	MSG.PRIORITY,
	NULL AS EXCL_GRP_ID,
	NULL AS EM_CHANNEL,
	NULL AS MC_CHANNEL,
	NULL AS OM_CHANNEL,
	NULL AS PN_CHANNEL,
	NULL AS HERO_MESSAGE_YN,
	NULL AS MESSAGE2_YN,
	NULL AS MESSAGE3_YN,
	NULL AS MESSAGE4_YN,
	NULL AS MESSAGE5_YN,
	NULL AS MESSAGE6_YN,
	NULL AS EXCLUDE_REASON_CD,
	CAST (CURRENT_DATE AS DATE FORMAT 'YYYY-MM-DD') AS DATA_DATE
FROM
	UNICA_TEMP.DE_FAMILY_MEN_RALLY_STG AS AUD
	
		INNER JOIN UNICA_TEMP.XMP_MAP_SEGMENT_MESSAGE AS MAP_SM
			ON	AUD.SEGM_ID = MAP_SM.SEGM_ID AND
					CURRENT_DATE BETWEEN MAP_SM.START_DATE-10 AND MAP_SM.END_DATE
					
		INNER JOIN UNICA_TEMP.XMP_MESSAGE AS MSG
			ON	MSG.MSG_ID = MAP_SM.MSG_ID AND
					CURRENT_DATE BETWEEN MSG.START_DATE-10 AND MSG.END_DATE AND
					MSG.MSG_NAME = 'DE_FM_RALLY001_OPTIN_150_INTRO'	
	WHERE 	EXCLUDE_REASON_CD IS NULL 
	AND RALLY_FLAG='TRUE' 
	AND POINTS<150
;

INSERT INTO UNICA_TEMP.DE_FM_RALLY_MESSAGE_STG
SELECT
      AUD.PRIMARY_USER_ID,
      AUD.DEMO_USER_ID,    
	AUD.AUD_ID,
	AUD.SEGM_ID,
	MSG.MSG_ID,
	NULL as JOURNEY_ID,
	NULL as SEQUENCE,	
	MSG.PRIORITY,
	NULL AS EXCL_GRP_ID,
	NULL AS EM_CHANNEL,
	NULL AS MC_CHANNEL,
	NULL AS OM_CHANNEL,
	NULL AS PN_CHANNEL,
	NULL AS HERO_MESSAGE_YN,
	NULL AS MESSAGE2_YN,
	NULL AS MESSAGE3_YN,
	NULL AS MESSAGE4_YN,
	NULL AS MESSAGE5_YN,
	NULL AS MESSAGE6_YN,
	NULL AS EXCLUDE_REASON_CD,
	CAST (CURRENT_DATE AS DATE FORMAT 'YYYY-MM-DD') AS DATA_DATE
FROM
	UNICA_TEMP.DE_FAMILY_MEN_RALLY_STG AS AUD
	
		INNER JOIN UNICA_TEMP.XMP_MAP_SEGMENT_MESSAGE AS MAP_SM
			ON	AUD.SEGM_ID = MAP_SM.SEGM_ID AND
					CURRENT_DATE BETWEEN MAP_SM.START_DATE-10 AND MAP_SM.END_DATE
					
		INNER JOIN UNICA_TEMP.XMP_MESSAGE AS MSG
			ON	MSG.MSG_ID = MAP_SM.MSG_ID AND
					CURRENT_DATE BETWEEN MSG.START_DATE-10 AND MSG.END_DATE AND
					MSG.MSG_NAME = 'DE_FM_RALLY002_OPTIN_999_INTRO'	
	WHERE 	EXCLUDE_REASON_CD IS NULL 
	AND RALLY_FLAG='TRUE' 
	AND POINTS between 150 and 999
;

INSERT INTO UNICA_TEMP.DE_FM_RALLY_MESSAGE_STG
SELECT
      AUD.PRIMARY_USER_ID,
      AUD.DEMO_USER_ID,    
	AUD.AUD_ID,
	AUD.SEGM_ID,
	MSG.MSG_ID,
	NULL as JOURNEY_ID,
	NULL as SEQUENCE,	
	MSG.PRIORITY,
	NULL AS EXCL_GRP_ID,
	NULL AS EM_CHANNEL,
	NULL AS MC_CHANNEL,
	NULL AS OM_CHANNEL,
	NULL AS PN_CHANNEL,
	NULL AS HERO_MESSAGE_YN,
	NULL AS MESSAGE2_YN,
	NULL AS MESSAGE3_YN,
	NULL AS MESSAGE4_YN,
	NULL AS MESSAGE5_YN,
	NULL AS MESSAGE6_YN,
	NULL AS EXCLUDE_REASON_CD,
	CAST (CURRENT_DATE AS DATE FORMAT 'YYYY-MM-DD') AS DATA_DATE
FROM
	UNICA_TEMP.DE_FAMILY_MEN_RALLY_STG AS AUD
	
		INNER JOIN UNICA_TEMP.XMP_MAP_SEGMENT_MESSAGE AS MAP_SM
			ON	AUD.SEGM_ID = MAP_SM.SEGM_ID AND
					CURRENT_DATE BETWEEN MAP_SM.START_DATE-10 AND MAP_SM.END_DATE
					
		INNER JOIN UNICA_TEMP.XMP_MESSAGE AS MSG
			ON	MSG.MSG_ID = MAP_SM.MSG_ID AND
					CURRENT_DATE BETWEEN MSG.START_DATE-10 AND MSG.END_DATE AND
					MSG.MSG_NAME = 'DE_FM_RALLY003_OPTIN_1000_INTRO'	
	WHERE 	EXCLUDE_REASON_CD IS NULL 
	AND RALLY_FLAG='TRUE' 
	AND POINTS > 999
;

INSERT INTO UNICA_TEMP.DE_FM_RALLY_MESSAGE_STG
SELECT
      AUD.PRIMARY_USER_ID,
      AUD.DEMO_USER_ID,    
	AUD.AUD_ID,
	AUD.SEGM_ID,
	MSG.MSG_ID,
	NULL as JOURNEY_ID,
	NULL as SEQUENCE,	
	MSG.PRIORITY,
	NULL AS EXCL_GRP_ID,
	NULL AS EM_CHANNEL,
	NULL AS MC_CHANNEL,
	NULL AS OM_CHANNEL,
	NULL AS PN_CHANNEL,
	NULL AS HERO_MESSAGE_YN,
	NULL AS MESSAGE2_YN,
	NULL AS MESSAGE3_YN,
	NULL AS MESSAGE4_YN,
	NULL AS MESSAGE5_YN,
	NULL AS MESSAGE6_YN,
	NULL AS EXCLUDE_REASON_CD,
	CAST (CURRENT_DATE AS DATE FORMAT 'YYYY-MM-DD') AS DATA_DATE
FROM
	UNICA_TEMP.DE_FAMILY_MEN_RALLY_STG AS AUD
	
		INNER JOIN UNICA_TEMP.XMP_MAP_SEGMENT_MESSAGE AS MAP_SM
			ON	AUD.SEGM_ID = MAP_SM.SEGM_ID AND
					CURRENT_DATE BETWEEN MAP_SM.START_DATE-10 AND MAP_SM.END_DATE
					
		INNER JOIN UNICA_TEMP.XMP_MESSAGE AS MSG
			ON	MSG.MSG_ID = MAP_SM.MSG_ID AND
					CURRENT_DATE BETWEEN MSG.START_DATE-10 AND MSG.END_DATE AND
					MSG.MSG_NAME = 'DE_FM_RALLY004_0_INTRO'	
	WHERE 	EXCLUDE_REASON_CD IS NULL 
	AND RALLY_FLAG='FALSE' 
	AND (POINTS = 0 or POINTS is NULL)
;

INSERT INTO UNICA_TEMP.DE_FM_RALLY_MESSAGE_STG
SELECT
      AUD.PRIMARY_USER_ID,
      AUD.DEMO_USER_ID,    
	AUD.AUD_ID,
	AUD.SEGM_ID,
	MSG.MSG_ID,
	NULL as JOURNEY_ID,
	NULL as SEQUENCE,	
	MSG.PRIORITY,
	NULL AS EXCL_GRP_ID,
	NULL AS EM_CHANNEL,
	NULL AS MC_CHANNEL,
	NULL AS OM_CHANNEL,
	NULL AS PN_CHANNEL,
	NULL AS HERO_MESSAGE_YN,
	NULL AS MESSAGE2_YN,
	NULL AS MESSAGE3_YN,
	NULL AS MESSAGE4_YN,
	NULL AS MESSAGE5_YN,
	NULL AS MESSAGE6_YN,
	NULL AS EXCLUDE_REASON_CD,
	CAST (CURRENT_DATE AS DATE FORMAT 'YYYY-MM-DD') AS DATA_DATE
FROM
	UNICA_TEMP.DE_FAMILY_MEN_RALLY_STG AS AUD
	
		INNER JOIN UNICA_TEMP.XMP_MAP_SEGMENT_MESSAGE AS MAP_SM
			ON	AUD.SEGM_ID = MAP_SM.SEGM_ID AND
					CURRENT_DATE BETWEEN MAP_SM.START_DATE-10 AND MAP_SM.END_DATE
					
		INNER JOIN UNICA_TEMP.XMP_MESSAGE AS MSG
			ON	MSG.MSG_ID = MAP_SM.MSG_ID AND
					CURRENT_DATE BETWEEN MSG.START_DATE-10 AND MSG.END_DATE AND
					MSG.MSG_NAME = 'DE_FM_RALLY005_POINTS_INTRO'	
		WHERE 	EXCLUDE_REASON_CD IS NULL 
	AND RALLY_FLAG='FALSE' 
	AND POINTS > 0 
;

INSERT INTO UNICA_TEMP.DE_FM_RALLY_MESSAGE_STG
SELECT
      AUD.PRIMARY_USER_ID,
      AUD.DEMO_USER_ID,    
	AUD.AUD_ID,
	AUD.SEGM_ID,
	MSG.MSG_ID,
	NULL as JOURNEY_ID,
	NULL as SEQUENCE,	
	MSG.PRIORITY,
	NULL AS EXCL_GRP_ID,
	NULL AS EM_CHANNEL,
	NULL AS MC_CHANNEL,
	NULL AS OM_CHANNEL,
	NULL AS PN_CHANNEL,
	NULL AS HERO_MESSAGE_YN,
	NULL AS MESSAGE2_YN,
	NULL AS MESSAGE3_YN,
	NULL AS MESSAGE4_YN,
	NULL AS MESSAGE5_YN,
	NULL AS MESSAGE6_YN,
	NULL AS EXCLUDE_REASON_CD,
	CAST (CURRENT_DATE AS DATE FORMAT 'YYYY-MM-DD') AS DATA_DATE
FROM
	UNICA_TEMP.DE_FAMILY_MEN_RALLY_STG AS AUD
	
		INNER JOIN UNICA_TEMP.XMP_MAP_SEGMENT_MESSAGE AS MAP_SM
			ON	AUD.SEGM_ID = MAP_SM.SEGM_ID AND
					CURRENT_DATE BETWEEN MAP_SM.START_DATE-10 AND MAP_SM.END_DATE
					
		INNER JOIN UNICA_TEMP.XMP_MESSAGE AS MSG
			ON	MSG.MSG_ID = MAP_SM.MSG_ID AND
					CURRENT_DATE BETWEEN MSG.START_DATE-10 AND MSG.END_DATE AND
					MSG.MSG_NAME = 'DE_FM_RALLY006_OPTIN_150_TURBOPOINTS'	
	WHERE 7=7
	AND  	EXCLUDE_REASON_CD IS NULL 
	AND RALLY_FLAG='TRUE' 
	AND POINTS <150
	
	
;

INSERT INTO UNICA_TEMP.DE_FM_RALLY_MESSAGE_STG
SELECT
      AUD.PRIMARY_USER_ID,
      AUD.DEMO_USER_ID,    
	AUD.AUD_ID,
	AUD.SEGM_ID,
	MSG.MSG_ID,
	NULL as JOURNEY_ID,
	NULL as SEQUENCE,	
	MSG.PRIORITY,
	NULL AS EXCL_GRP_ID,
	NULL AS EM_CHANNEL,
	NULL AS MC_CHANNEL,
	NULL AS OM_CHANNEL,
	NULL AS PN_CHANNEL,
	NULL AS HERO_MESSAGE_YN,
	NULL AS MESSAGE2_YN,
	NULL AS MESSAGE3_YN,
	NULL AS MESSAGE4_YN,
	NULL AS MESSAGE5_YN,
	NULL AS MESSAGE6_YN,
	NULL AS EXCLUDE_REASON_CD,
	CAST (CURRENT_DATE AS DATE FORMAT 'YYYY-MM-DD') AS DATA_DATE
FROM
	UNICA_TEMP.DE_FAMILY_MEN_RALLY_STG AS AUD
	
		INNER JOIN UNICA_TEMP.XMP_MAP_SEGMENT_MESSAGE AS MAP_SM
			ON	AUD.SEGM_ID = MAP_SM.SEGM_ID AND
					CURRENT_DATE BETWEEN MAP_SM.START_DATE-10 AND MAP_SM.END_DATE
					
		INNER JOIN UNICA_TEMP.XMP_MESSAGE AS MSG
			ON	MSG.MSG_ID = MAP_SM.MSG_ID AND
					CURRENT_DATE BETWEEN MSG.START_DATE-10 AND MSG.END_DATE AND
					MSG.MSG_NAME = 'DE_FM_RALLY007_OPTIN_199_TURBOPOINTS'	
	WHERE 7=7
	AND EXCLUDE_REASON_CD IS NULL 
	AND RALLY_FLAG='TRUE' 
	AND POINTS >=150
	AND POINTS <200
;

INSERT INTO UNICA_TEMP.DE_FM_RALLY_MESSAGE_STG
SELECT
      AUD.PRIMARY_USER_ID,
      AUD.DEMO_USER_ID,    
	AUD.AUD_ID,
	AUD.SEGM_ID,
	MSG.MSG_ID,
	NULL as JOURNEY_ID,
	NULL as SEQUENCE,	
	MSG.PRIORITY,
	NULL AS EXCL_GRP_ID,
	NULL AS EM_CHANNEL,
	NULL AS MC_CHANNEL,
	NULL AS OM_CHANNEL,
	NULL AS PN_CHANNEL,
	NULL AS HERO_MESSAGE_YN,
	NULL AS MESSAGE2_YN,
	NULL AS MESSAGE3_YN,
	NULL AS MESSAGE4_YN,
	NULL AS MESSAGE5_YN,
	NULL AS MESSAGE6_YN,
	NULL AS EXCLUDE_REASON_CD,
	CAST (CURRENT_DATE AS DATE FORMAT 'YYYY-MM-DD') AS DATA_DATE
FROM
	UNICA_TEMP.DE_FAMILY_MEN_RALLY_STG AS AUD
	
		INNER JOIN UNICA_TEMP.XMP_MAP_SEGMENT_MESSAGE AS MAP_SM
			ON	AUD.SEGM_ID = MAP_SM.SEGM_ID AND
					CURRENT_DATE BETWEEN MAP_SM.START_DATE-10 AND MAP_SM.END_DATE
					
		INNER JOIN UNICA_TEMP.XMP_MESSAGE AS MSG
			ON	MSG.MSG_ID = MAP_SM.MSG_ID AND
					CURRENT_DATE BETWEEN MSG.START_DATE-10 AND MSG.END_DATE AND
					MSG.MSG_NAME = 'DE_FM_RALLY008_OPTIN_299_TURBOPOINTS'	
	WHERE 7=7
	AND  	EXCLUDE_REASON_CD IS NULL 
	AND RALLY_FLAG='TRUE' 
	AND POINTS >=200
	AND POINTS <300
;


INSERT INTO UNICA_TEMP.DE_FM_RALLY_MESSAGE_STG
SELECT
      AUD.PRIMARY_USER_ID,
      AUD.DEMO_USER_ID,    
	AUD.AUD_ID,
	AUD.SEGM_ID,
	MSG.MSG_ID,
	NULL as JOURNEY_ID,
	NULL as SEQUENCE,	
	MSG.PRIORITY,
	NULL AS EXCL_GRP_ID,
	NULL AS EM_CHANNEL,
	NULL AS MC_CHANNEL,
	NULL AS OM_CHANNEL,
	NULL AS PN_CHANNEL,
	NULL AS HERO_MESSAGE_YN,
	NULL AS MESSAGE2_YN,
	NULL AS MESSAGE3_YN,
	NULL AS MESSAGE4_YN,
	NULL AS MESSAGE5_YN,
	NULL AS MESSAGE6_YN,
	NULL AS EXCLUDE_REASON_CD,
	CAST (CURRENT_DATE AS DATE FORMAT 'YYYY-MM-DD') AS DATA_DATE
FROM
	UNICA_TEMP.DE_FAMILY_MEN_RALLY_STG AS AUD
	
		INNER JOIN UNICA_TEMP.XMP_MAP_SEGMENT_MESSAGE AS MAP_SM
			ON	AUD.SEGM_ID = MAP_SM.SEGM_ID AND
					CURRENT_DATE BETWEEN MAP_SM.START_DATE-10 AND MAP_SM.END_DATE
					
		INNER JOIN UNICA_TEMP.XMP_MESSAGE AS MSG
			ON	MSG.MSG_ID = MAP_SM.MSG_ID AND
					CURRENT_DATE BETWEEN MSG.START_DATE-10 AND MSG.END_DATE AND
					MSG.MSG_NAME = 'DE_FM_RALLY009_OPTIN_499TURBOPOINTS'	
	WHERE 7=7
	AND  	EXCLUDE_REASON_CD IS NULL 
	AND RALLY_FLAG='TRUE' 
	AND POINTS >=300
	AND POINTS <500
;

INSERT INTO UNICA_TEMP.DE_FM_RALLY_MESSAGE_STG
SELECT
      AUD.PRIMARY_USER_ID,
      AUD.DEMO_USER_ID,    
	AUD.AUD_ID,
	AUD.SEGM_ID,
	MSG.MSG_ID,
	NULL as JOURNEY_ID,
	NULL as SEQUENCE,	
	MSG.PRIORITY,
	NULL AS EXCL_GRP_ID,
	NULL AS EM_CHANNEL,
	NULL AS MC_CHANNEL,
	NULL AS OM_CHANNEL,
	NULL AS PN_CHANNEL,
	NULL AS HERO_MESSAGE_YN,
	NULL AS MESSAGE2_YN,
	NULL AS MESSAGE3_YN,
	NULL AS MESSAGE4_YN,
	NULL AS MESSAGE5_YN,
	NULL AS MESSAGE6_YN,
	NULL AS EXCLUDE_REASON_CD,
	CAST (CURRENT_DATE AS DATE FORMAT 'YYYY-MM-DD') AS DATA_DATE
FROM
	UNICA_TEMP.DE_FAMILY_MEN_RALLY_STG AS AUD
	
		INNER JOIN UNICA_TEMP.XMP_MAP_SEGMENT_MESSAGE AS MAP_SM
			ON	AUD.SEGM_ID = MAP_SM.SEGM_ID AND
					CURRENT_DATE BETWEEN MAP_SM.START_DATE-10 AND MAP_SM.END_DATE
					
		INNER JOIN UNICA_TEMP.XMP_MESSAGE AS MSG
			ON	MSG.MSG_ID = MAP_SM.MSG_ID AND
					CURRENT_DATE BETWEEN MSG.START_DATE-10 AND MSG.END_DATE AND
					MSG.MSG_NAME = 'DE_FM_RALLY010_OPTIN_999_TURBOPOINTS'	
	WHERE 7=7
	AND 	EXCLUDE_REASON_CD IS NULL 
	AND RALLY_FLAG='TRUE' 
	AND POINTS >=500
	AND POINTS <1000
;

INSERT INTO UNICA_TEMP.DE_FM_RALLY_MESSAGE_STG
SELECT
      AUD.PRIMARY_USER_ID,
      AUD.DEMO_USER_ID,    
	AUD.AUD_ID,
	AUD.SEGM_ID,
	MSG.MSG_ID,
	NULL as JOURNEY_ID,
	NULL as SEQUENCE,	
	MSG.PRIORITY,
	NULL AS EXCL_GRP_ID,
	NULL AS EM_CHANNEL,
	NULL AS MC_CHANNEL,
	NULL AS OM_CHANNEL,
	NULL AS PN_CHANNEL,
	NULL AS HERO_MESSAGE_YN,
	NULL AS MESSAGE2_YN,
	NULL AS MESSAGE3_YN,
	NULL AS MESSAGE4_YN,
	NULL AS MESSAGE5_YN,
	NULL AS MESSAGE6_YN,
	NULL AS EXCLUDE_REASON_CD,
	CAST (CURRENT_DATE AS DATE FORMAT 'YYYY-MM-DD') AS DATA_DATE
FROM
	UNICA_TEMP.DE_FAMILY_MEN_RALLY_STG AS AUD
	
		INNER JOIN UNICA_TEMP.XMP_MAP_SEGMENT_MESSAGE AS MAP_SM
			ON	AUD.SEGM_ID = MAP_SM.SEGM_ID AND
					CURRENT_DATE BETWEEN MAP_SM.START_DATE-10 AND MAP_SM.END_DATE
					
		INNER JOIN UNICA_TEMP.XMP_MESSAGE AS MSG
			ON	MSG.MSG_ID = MAP_SM.MSG_ID AND
					CURRENT_DATE BETWEEN MSG.START_DATE-10 AND MSG.END_DATE AND
					MSG.MSG_NAME = 'DE_FM_RALLY011_OPTIN_1000_TURBOPOINTS'	
	WHERE 7=7
	AND EXCLUDE_REASON_CD IS NULL 
	AND RALLY_FLAG='TRUE' 
	AND POINTS >=1000
	
;

INSERT INTO UNICA_TEMP.DE_FM_RALLY_MESSAGE_STG
SELECT
      AUD.PRIMARY_USER_ID,
      AUD.DEMO_USER_ID,    
	AUD.AUD_ID,
	AUD.SEGM_ID,
	MSG.MSG_ID,
	NULL as JOURNEY_ID,
	NULL as SEQUENCE,	
	MSG.PRIORITY,
	NULL AS EXCL_GRP_ID,
	NULL AS EM_CHANNEL,
	NULL AS MC_CHANNEL,
	NULL AS OM_CHANNEL,
	NULL AS PN_CHANNEL,
	NULL AS HERO_MESSAGE_YN,
	NULL AS MESSAGE2_YN,
	NULL AS MESSAGE3_YN,
	NULL AS MESSAGE4_YN,
	NULL AS MESSAGE5_YN,
	NULL AS MESSAGE6_YN,
	NULL AS EXCLUDE_REASON_CD,
	CAST (CURRENT_DATE AS DATE FORMAT 'YYYY-MM-DD') AS DATA_DATE
FROM
	UNICA_TEMP.DE_FAMILY_MEN_RALLY_STG AS AUD
	
		INNER JOIN UNICA_TEMP.XMP_MAP_SEGMENT_MESSAGE AS MAP_SM
			ON	AUD.SEGM_ID = MAP_SM.SEGM_ID AND
					CURRENT_DATE BETWEEN MAP_SM.START_DATE-10 AND MAP_SM.END_DATE
					
		INNER JOIN  UNICA_TEMP.XMP_MESSAGE AS MSG
			ON	MSG.MSG_ID = MAP_SM.MSG_ID AND
					CURRENT_DATE BETWEEN MSG.START_DATE-10 AND MSG.END_DATE AND
					MSG.MSG_NAME = 'DE_FM_RALLY012_0_TURBOPOINTS'	
	WHERE 7=7
	AND 	EXCLUDE_REASON_CD IS NULL 
	AND RALLY_FLAG='FALSE' 
	AND (POINTS =0 or POINTS is NULL)
;

INSERT INTO UNICA_TEMP.DE_FM_RALLY_MESSAGE_STG
SELECT
      AUD.PRIMARY_USER_ID,
      AUD.DEMO_USER_ID,    
	AUD.AUD_ID,
	AUD.SEGM_ID,
	MSG.MSG_ID,
	NULL as JOURNEY_ID,
	NULL as SEQUENCE,	
	MSG.PRIORITY,
	NULL AS EXCL_GRP_ID,
	NULL AS EM_CHANNEL,
	NULL AS MC_CHANNEL,
	NULL AS OM_CHANNEL,
	NULL AS PN_CHANNEL,
	NULL AS HERO_MESSAGE_YN,
	NULL AS MESSAGE2_YN,
	NULL AS MESSAGE3_YN,
	NULL AS MESSAGE4_YN,
	NULL AS MESSAGE5_YN,
	NULL AS MESSAGE6_YN,
	NULL AS EXCLUDE_REASON_CD,
	CAST (CURRENT_DATE AS DATE FORMAT 'YYYY-MM-DD') AS DATA_DATE
FROM
	UNICA_TEMP.DE_FAMILY_MEN_RALLY_STG AS AUD
	
		INNER JOIN UNICA_TEMP.XMP_MAP_SEGMENT_MESSAGE AS MAP_SM
			ON	AUD.SEGM_ID = MAP_SM.SEGM_ID AND
					CURRENT_DATE BETWEEN MAP_SM.START_DATE-10 AND MAP_SM.END_DATE
					
		INNER JOIN UNICA_TEMP.XMP_MESSAGE AS MSG
			ON	MSG.MSG_ID = MAP_SM.MSG_ID AND
					CURRENT_DATE BETWEEN MSG.START_DATE-10 AND MSG.END_DATE AND
					MSG.MSG_NAME = 'DE_FM_RALLY013_150_TURBOPOINTS'	
		WHERE 7=7
	AND 	EXCLUDE_REASON_CD IS NULL 
	AND RALLY_FLAG='FALSE' 
	AND POINTS >0
	AND POINTS <150
;

INSERT INTO UNICA_TEMP.DE_FM_RALLY_MESSAGE_STG
SELECT
      AUD.PRIMARY_USER_ID,
      AUD.DEMO_USER_ID,    
	AUD.AUD_ID,
	AUD.SEGM_ID,
	MSG.MSG_ID,
	NULL as JOURNEY_ID,
	NULL as SEQUENCE,	
	MSG.PRIORITY,
	NULL AS EXCL_GRP_ID,
	NULL AS EM_CHANNEL,
	NULL AS MC_CHANNEL,
	NULL AS OM_CHANNEL,
	NULL AS PN_CHANNEL,
	NULL AS HERO_MESSAGE_YN,
	NULL AS MESSAGE2_YN,
	NULL AS MESSAGE3_YN,
	NULL AS MESSAGE4_YN,
	NULL AS MESSAGE5_YN,
	NULL AS MESSAGE6_YN,
	NULL AS EXCLUDE_REASON_CD,
	CAST (CURRENT_DATE AS DATE FORMAT 'YYYY-MM-DD') AS DATA_DATE
FROM
	UNICA_TEMP.DE_FAMILY_MEN_RALLY_STG AS AUD
	
		INNER JOIN UNICA_TEMP.XMP_MAP_SEGMENT_MESSAGE AS MAP_SM
			ON	AUD.SEGM_ID = MAP_SM.SEGM_ID AND
					CURRENT_DATE BETWEEN MAP_SM.START_DATE-10 AND MAP_SM.END_DATE
					
		INNER JOIN UNICA_TEMP.XMP_MESSAGE AS MSG
			ON	MSG.MSG_ID = MAP_SM.MSG_ID AND
					CURRENT_DATE BETWEEN MSG.START_DATE-10 AND MSG.END_DATE AND
					MSG.MSG_NAME = 'DE_FM_RALLY014_199_TURBOPOINTS'	
		WHERE 7=7
	AND  	EXCLUDE_REASON_CD IS NULL 
	AND RALLY_FLAG='FALSE' 
	AND POINTS >=150
	AND POINTS <200
;

INSERT INTO UNICA_TEMP.DE_FM_RALLY_MESSAGE_STG
SELECT
      AUD.PRIMARY_USER_ID,
      AUD.DEMO_USER_ID,    
	AUD.AUD_ID,
	AUD.SEGM_ID,
	MSG.MSG_ID,
	NULL as JOURNEY_ID,
	NULL as SEQUENCE,	
	MSG.PRIORITY,
	NULL AS EXCL_GRP_ID,
	NULL AS EM_CHANNEL,
	NULL AS MC_CHANNEL,
	NULL AS OM_CHANNEL,
	NULL AS PN_CHANNEL,
	NULL AS HERO_MESSAGE_YN,
	NULL AS MESSAGE2_YN,
	NULL AS MESSAGE3_YN,
	NULL AS MESSAGE4_YN,
	NULL AS MESSAGE5_YN,
	NULL AS MESSAGE6_YN,
	NULL AS EXCLUDE_REASON_CD,
	CAST (CURRENT_DATE AS DATE FORMAT 'YYYY-MM-DD') AS DATA_DATE
FROM
	UNICA_TEMP.DE_FAMILY_MEN_RALLY_STG AS AUD
	
		INNER JOIN UNICA_TEMP.XMP_MAP_SEGMENT_MESSAGE AS MAP_SM
			ON	AUD.SEGM_ID = MAP_SM.SEGM_ID AND
					CURRENT_DATE BETWEEN MAP_SM.START_DATE-10 AND MAP_SM.END_DATE
					
		INNER JOIN UNICA_TEMP.XMP_MESSAGE AS MSG
			ON	MSG.MSG_ID = MAP_SM.MSG_ID AND
					CURRENT_DATE BETWEEN MSG.START_DATE-10 AND MSG.END_DATE AND
					MSG.MSG_NAME = 'DE_FM_RALLY015_299_TURBOPOINTS'	
		WHERE 7=7
	AND  	EXCLUDE_REASON_CD IS NULL 
	AND RALLY_FLAG='FALSE' 
	AND POINTS >=200
	AND POINTS <299
;

INSERT INTO UNICA_TEMP.DE_FM_RALLY_MESSAGE_STG
SELECT
      AUD.PRIMARY_USER_ID,
      AUD.DEMO_USER_ID,    
	AUD.AUD_ID,
	AUD.SEGM_ID,
	MSG.MSG_ID,
	NULL as JOURNEY_ID,
	NULL as SEQUENCE,	
	MSG.PRIORITY,
	NULL AS EXCL_GRP_ID,
	NULL AS EM_CHANNEL,
	NULL AS MC_CHANNEL,
	NULL AS OM_CHANNEL,
	NULL AS PN_CHANNEL,
	NULL AS HERO_MESSAGE_YN,
	NULL AS MESSAGE2_YN,
	NULL AS MESSAGE3_YN,
	NULL AS MESSAGE4_YN,
	NULL AS MESSAGE5_YN,
	NULL AS MESSAGE6_YN,
	NULL AS EXCLUDE_REASON_CD,
	CAST (CURRENT_DATE AS DATE FORMAT 'YYYY-MM-DD') AS DATA_DATE
FROM
	UNICA_TEMP.DE_FAMILY_MEN_RALLY_STG AS AUD
	
		INNER JOIN UNICA_TEMP.XMP_MAP_SEGMENT_MESSAGE AS MAP_SM
			ON	AUD.SEGM_ID = MAP_SM.SEGM_ID AND
					CURRENT_DATE BETWEEN MAP_SM.START_DATE-10 AND MAP_SM.END_DATE
					
		INNER JOIN UNICA_TEMP.XMP_MESSAGE AS MSG
			ON	MSG.MSG_ID = MAP_SM.MSG_ID AND
					CURRENT_DATE BETWEEN MSG.START_DATE-10 AND MSG.END_DATE AND
					MSG.MSG_NAME = 'DE_FM_RALLY016_499_TURBOPOINTS'	
		WHERE 7=7
	AND  	EXCLUDE_REASON_CD IS NULL 
	AND RALLY_FLAG='FALSE' 
	AND POINTS >=300
	AND POINTS <500
;

INSERT INTO UNICA_TEMP.DE_FM_RALLY_MESSAGE_STG
SELECT
      AUD.PRIMARY_USER_ID,
      AUD.DEMO_USER_ID,    
	AUD.AUD_ID,
	AUD.SEGM_ID,
	MSG.MSG_ID,
	NULL as JOURNEY_ID,
	NULL as SEQUENCE,	
	MSG.PRIORITY,
	NULL AS EXCL_GRP_ID,
	NULL AS EM_CHANNEL,
	NULL AS MC_CHANNEL,
	NULL AS OM_CHANNEL,
	NULL AS PN_CHANNEL,
	NULL AS HERO_MESSAGE_YN,
	NULL AS MESSAGE2_YN,
	NULL AS MESSAGE3_YN,
	NULL AS MESSAGE4_YN,
	NULL AS MESSAGE5_YN,
	NULL AS MESSAGE6_YN,
	NULL AS EXCLUDE_REASON_CD,
	CAST (CURRENT_DATE AS DATE FORMAT 'YYYY-MM-DD') AS DATA_DATE
FROM
	UNICA_TEMP.DE_FAMILY_MEN_RALLY_STG AS AUD
	
		INNER JOIN UNICA_TEMP.XMP_MAP_SEGMENT_MESSAGE AS MAP_SM
			ON	AUD.SEGM_ID = MAP_SM.SEGM_ID AND
					CURRENT_DATE BETWEEN MAP_SM.START_DATE-10 AND MAP_SM.END_DATE
					
		INNER JOIN UNICA_TEMP.XMP_MESSAGE AS MSG
			ON	MSG.MSG_ID = MAP_SM.MSG_ID AND
					CURRENT_DATE BETWEEN MSG.START_DATE-10 AND MSG.END_DATE AND
					MSG.MSG_NAME = 'DE_FM_RALLY017_999_TURBOPOINTS'	
		WHERE 7=7
	AND  	EXCLUDE_REASON_CD IS NULL 
	AND RALLY_FLAG='FALSE' 
	AND POINTS >=500
	AND POINTS <1000
;

INSERT INTO UNICA_TEMP.DE_FM_RALLY_MESSAGE_STG
SELECT
      AUD.PRIMARY_USER_ID,
      AUD.DEMO_USER_ID,    
	AUD.AUD_ID,
	AUD.SEGM_ID,
	MSG.MSG_ID,
	NULL as JOURNEY_ID,
	NULL as SEQUENCE,	
	MSG.PRIORITY,
	NULL AS EXCL_GRP_ID,
	NULL AS EM_CHANNEL,
	NULL AS MC_CHANNEL,
	NULL AS OM_CHANNEL,
	NULL AS PN_CHANNEL,
	NULL AS HERO_MESSAGE_YN,
	NULL AS MESSAGE2_YN,
	NULL AS MESSAGE3_YN,
	NULL AS MESSAGE4_YN,
	NULL AS MESSAGE5_YN,
	NULL AS MESSAGE6_YN,
	NULL AS EXCLUDE_REASON_CD,
	CAST (CURRENT_DATE AS DATE FORMAT 'YYYY-MM-DD') AS DATA_DATE
FROM
	UNICA_TEMP.DE_FAMILY_MEN_RALLY_STG AS AUD
	
		INNER JOIN UNICA_TEMP.XMP_MAP_SEGMENT_MESSAGE AS MAP_SM
			ON	AUD.SEGM_ID = MAP_SM.SEGM_ID AND
					CURRENT_DATE BETWEEN MAP_SM.START_DATE-10 AND MAP_SM.END_DATE
					
		INNER JOIN UNICA_TEMP.XMP_MESSAGE AS MSG
			ON	MSG.MSG_ID = MAP_SM.MSG_ID AND
					CURRENT_DATE BETWEEN MSG.START_DATE-10 AND MSG.END_DATE AND
					MSG.MSG_NAME = 'DE_FM_RALLY018_1000_TURBOPOINTS'	
		WHERE 7=7
	AND  	EXCLUDE_REASON_CD IS NULL 
	AND RALLY_FLAG='FALSE' 
	AND POINTS >=1000
;

INSERT INTO UNICA_TEMP.DE_FM_RALLY_MESSAGE_STG
SELECT
      AUD.PRIMARY_USER_ID,
      AUD.DEMO_USER_ID,    
	AUD.AUD_ID,
	AUD.SEGM_ID,
	MSG.MSG_ID,
	NULL as JOURNEY_ID,
	NULL as SEQUENCE,	
	MSG.PRIORITY,
	NULL AS EXCL_GRP_ID,
	NULL AS EM_CHANNEL,
	NULL AS MC_CHANNEL,
	NULL AS OM_CHANNEL,
	NULL AS PN_CHANNEL,
	NULL AS HERO_MESSAGE_YN,
	NULL AS MESSAGE2_YN,
	NULL AS MESSAGE3_YN,
	NULL AS MESSAGE4_YN,
	NULL AS MESSAGE5_YN,
	NULL AS MESSAGE6_YN,
	NULL AS EXCLUDE_REASON_CD,
	CAST (CURRENT_DATE AS DATE FORMAT 'YYYY-MM-DD') AS DATA_DATE
FROM
	UNICA_TEMP.DE_FAMILY_MEN_RALLY_STG AS AUD
	
		INNER JOIN UNICA_TEMP.XMP_MAP_SEGMENT_MESSAGE AS MAP_SM
			ON	AUD.SEGM_ID = MAP_SM.SEGM_ID AND
					CURRENT_DATE BETWEEN MAP_SM.START_DATE-10 AND MAP_SM.END_DATE
					
		INNER JOIN UNICA_TEMP.XMP_MESSAGE AS MSG
			ON	MSG.MSG_ID = MAP_SM.MSG_ID AND
					CURRENT_DATE BETWEEN MSG.START_DATE-10 AND MSG.END_DATE AND
					MSG.MSG_NAME = 'DE_FM_RALLY019_EVENTS_MODUL'	
		WHERE 7=7
	AND  	EXCLUDE_REASON_CD IS NULL 

;
UPDATE	UNICA_TEMP.DE_FM_RALLY_MESSAGE_STG
FROM 	UNICA_TEMP.DE_FM_MESSAGE_PLACEMENT AS PLAC
SET
	HERO_MESSAGE_YN = PLAC.HERO_MESSAGE_YN,
	MESSAGE2_YN = PLAC.MESSAGE2_YN,
	MESSAGE3_YN = PLAC.MESSAGE3_YN
WHERE UNICA_TEMP.DE_FM_RALLY_MESSAGE_STG.MSG_ID = PLAC.MSG_ID
;

/*UPDATE CHANNELS*/
UPDATE	UNICA_TEMP.DE_FM_RALLY_MESSAGE_STG
FROM		UNICA_TEMP.XMP_MESSAGE_CHANNEL AS CHNL
SET
	EM_CHANNEL = CHNL.EM_CHANNEL,
	MC_CHANNEL = CHNL.MC_CHANNEL,
	OM_CHANNEL = CHNL.OM_CHANNEL,
	PN_CHANNEL = CHNL.PN_CHANNEL
WHERE UNICA_TEMP.DE_FM_RALLY_MESSAGE_STG.MSG_ID = CHNL.MSG_ID
;
/*EXCLUDE USERS WHO DON'T HAVE ENOUGH MESSAGES*/
UPDATE	UNICA_TEMP.DE_FM_RALLY_MESSAGE_STG
FROM		(
				SELECT PRIMARY_USER_ID,AUD_ID,SEGM_ID, COUNT(*) AS USR_CNT
				FROM UNICA_TEMP.DE_FM_RALLY_MESSAGE_STG
				GROUP BY 1,2,3
				HAVING USR_CNT < 3
				) AS EXC
SET	EXCLUDE_REASON_CD = 44
WHERE
	UNICA_TEMP.DE_FM_RALLY_MESSAGE_STG.PRIMARY_USER_ID = EXC.PRIMARY_USER_ID AND
	UNICA_TEMP.DE_FM_RALLY_MESSAGE_STG.AUD_ID = EXC.AUD_ID AND
	UNICA_TEMP.DE_FM_RALLY_MESSAGE_STG.SEGM_ID = EXC.SEGM_ID 
;
--sel distinct demo_user_id from UNICA_TEMP.DE_FM_RALLY_MESSAGE_STG where  HERO_MESSAGE_YN = 'Y'

 /*************************************************************************************************
INSERTING INTO EMAIL STAGING TABLE
***************************************************************************************************/
	
DELETE FROM UNICA_TEMP.DE_FM_RALLY_TARGETING_EM_STG ALL;
 
 INSERT INTO UNICA_TEMP.DE_FM_RALLY_TARGETING_EM_STG
 SELECT
	STG.PRIMARY_USER_ID,
	STG.DEMO_USER_ID,
	STG.AUD_ID,
	STG.SEGM_ID,
	STG.JOURNEY_ID AS JOURNEY_ID,
	STG.SEQUENCE AS SEQUENCE,
	STG.MSG_ID AS HERO_MESSAGE,
	NULL AS MESSAGE2,
	NULL AS MESSAGE3,
	NULL AS EXCLUDE_REASON_CD,
	POINTS  as PLUS_POINTS,
	PULL_DATE as REWARDS_DATE,
	'T' as TC,
	'N' as CH_EMAIL_YN,
	'N' as CH_MC_YN,
	STG.DATA_DATE	
FROM
	UNICA_TEMP.DE_FM_RALLY_MESSAGE_STG STG
	JOIN  UNICA_TEMP.DE_FAMILY_MEN_RALLY_STG DAILY on STG.DEMO_USER_ID=DAILY.DEMO_USER_ID
WHERE
	STG.EXCLUDE_REASON_CD IS NULL 
	AND HERO_MESSAGE_YN = 'Y'
GROUP BY
	STG.PRIMARY_USER_ID,
	STG.DEMO_USER_ID,
	STG.AUD_ID,
	STG.SEGM_ID,
	STG.JOURNEY_ID,
	STG.SEQUENCE,
	STG.MSG_ID,
	POINTS,
	PULL_DATE,
	STG.DATA_DATE
;	

UPDATE UNICA_TEMP.DE_FM_RALLY_TARGETING_EM_STG
FROM UNICA_TEMP.DE_FM_RALLY_MESSAGE_STG AS B
 SET 
	MESSAGE2=B.MSG_ID
WHERE
	UNICA_TEMP.DE_FM_RALLY_TARGETING_EM_STG.PRIMARY_USER_ID = B.PRIMARY_USER_ID AND
	B.MESSAGE2_YN = 'Y' AND
	B.EXCLUDE_REASON_CD IS NULL
;

UPDATE UNICA_TEMP.DE_FM_RALLY_TARGETING_EM_STG
FROM UNICA_TEMP.DE_FM_RALLY_MESSAGE_STG AS B
 SET 
	MESSAGE3=B.MSG_ID
WHERE
	UNICA_TEMP.DE_FM_RALLY_TARGETING_EM_STG.PRIMARY_USER_ID = B.PRIMARY_USER_ID AND
	B.MESSAGE3_YN = 'Y'
;


--MC FLAG
UPDATE A FROM UNICA_TEMP.DE_FM_RALLY_TARGETING_EM_STG AS A
SET
	CH_MC_YN =  'Y'
	
WHERE 	CH_MC_YN =  'N' AND
			EXISTS	(
						SELECT *
						FROM PRS_SECURE_V.MDM_USER_PII AS PII
						WHERE (PII.MSGCENTER_PROMOSOFFERSEVENTS = 'Y'   
						or user_slctd_id  in (
'mogucan',  --Gybasova, Kristina
'marieck_6',  --Eckert, Thomas
'sraudschus', --Peijan, Stefanie
'emnewman', --Newman, Emma
'mllewiwa', --(Kristin Wyrwa)
'the9280', -- (Theresa Thüs)
'sa-32439' , --(Sandy Kim)
'kathihartung832',
'marekmk', 
'dmalhao@ebay.com',
'psperling@ebay.de',  
'steffisoleil84'))
						AND A.DEMO_USER_ID = PII.USER_ID
						)
;

--NON-RESPONDER FLAG
UPDATE A FROM UNICA_TEMP.DE_FM_RALLY_TARGETING_EM_STG AS A
SET
	EXCLUDE_REASON_CD =  45
	
WHERE 	EXCLUDE_REASON_CD IS NULL AND
			EXISTS	(
						SELECT *
						FROM PRS_SECURE_V.MDM_USER_PII AS PII
						WHERE PII.RSPNDR_YN = 'N' AND A.DEMO_USER_ID = PII.USER_ID
						)
;
						
--BLACKLIST FLAG
UPDATE A FROM UNICA_TEMP.DE_FM_RALLY_TARGETING_EM_STG AS A
SET
	EXCLUDE_REASON_CD =  50
	
WHERE 	EXCLUDE_REASON_CD IS NULL AND
			EXISTS	(
						SELECT *
						FROM PRS_SECURE_V.MDM_USER_PII AS PII
						WHERE PII.BLCKLST_YN = 'Y' AND A.DEMO_USER_ID = PII.USER_ID
						)
;
						
--UNDELIVERABLE FLAG
UPDATE A FROM UNICA_TEMP.DE_FM_RALLY_TARGETING_EM_STG AS A
SET
	EXCLUDE_REASON_CD =  55
	
WHERE 	EXCLUDE_REASON_CD IS NULL AND
			EXISTS	(
						SELECT *
						FROM PRS_SECURE_V.MDM_USER_PII AS PII
						WHERE PII.DLVRABLE_YN = 'N' AND A.DEMO_USER_ID = PII.USER_ID
						and user_slctd_id not in (
'mogucan',  --Gybasova, Kristina
'marieck_6',  --Eckert, Thomas
'sraudschus', --Peijan, Stefanie
'emnewman', --Newman, Emma
'mllewiwa', --(Kristin Wyrwa)
'the9280', -- (Theresa Thüs)
'sa-32439' , --(Sandy Kim)
'kathihartung832',
'marekmk', 
'dmalhao@ebay.com',
'psperling@ebay.de',  
'steffisoleil84')
						)
;

--ACTIVITY FLAG
UPDATE A FROM UNICA_TEMP.DE_FM_RALLY_TARGETING_EM_STG AS A
SET
	EXCLUDE_REASON_CD =  60
	
WHERE 	EXCLUDE_REASON_CD IS NULL AND
			EXISTS	(
						SELECT *
						FROM PRS_SECURE_V.MDM_USER_PII AS PII
						WHERE PII.ACTV_YN = 'N' AND A.DEMO_USER_ID = PII.USER_ID
						)
;
						
--EMAIL MASTER PREFERENCE FLAG
UPDATE A FROM UNICA_TEMP.DE_FM_RALLY_TARGETING_EM_STG AS A
SET
	EXCLUDE_REASON_CD =  65
	
WHERE 	EXCLUDE_REASON_CD IS NULL AND
			EXISTS	(
						SELECT *
						FROM PRS_SECURE_V.MDM_USER_PII AS PII
						WHERE PII.EMAIL_MAST_PREF_YN = 'N' AND A.DEMO_USER_ID = PII.USER_ID 
						AND user_slctd_id not in (
'mogucan',  --Gybasova, Kristina
'marieck_6',  --Eckert, Thomas
'sraudschus', --Peijan, Stefanie
'emnewman', --Newman, Emma
'mllewiwa', --(Kristin Wyrwa)
'the9280', -- (Theresa Thüs)
'sa-32439' , --(Sandy Kim)
'kathihartung832',
'marekmk', 
'dmalhao@ebay.com',
'psperling@ebay.de',  
'steffisoleil84')
						);

				UPDATE A FROM UNICA_TEMP.DE_FM_RALLY_TARGETING_EM_STG AS A
SET
	CH_EMAIL_YN =  'Y'
	
WHERE 	EXCLUDE_REASON_CD IS NULL 
		
						
--sel * from UNICA_TEMP.DE_FM_RALLY_TARGETING_EM_STG;						



/*

--EM archiv
INSERT INTO  UNICA_TEMP.DE_FM_TARGETING_EM_ARCHIV 
SELECT * from UNICA_TEMP.DE_FM_TARGETING_DAILY_EM
;*/
--ALL archiv
INSERT INTO   UNICA_TEMP.DE_FM_RALLY_TARGETING_ALL_ARCHIV 
SELECT * from UNICA_TEMP.DE_FM_RALLY_TARGETING_EM_STG a 
;


/*
SELECT TC, HERO_MESSAGE,
	MESSAGE2,
	MESSAGE3,
	count(demo_user_id) FROM UNICA_TEMP.DE_FM_RALLY_TARGETING_EM_STG 
	WHERE CH_EMAIL_YN='Y' 
	group by 1,2,3,4;
	
	SELECT TC, HERO_MESSAGE,
	MESSAGE2,
	MESSAGE3,
	count(demo_user_id) FROM UNICA_TEMP.DE_FM_RALLY_TARGETING_EM_STG 
	WHERE CH_MC_YN='Y' 
	group by 1,2,3,4;
	
	
	select exclude_reason_cd, count(demo_user_id) from UNICA_TEMP.DE_FAMILY_MEN_RALLY_STG  group by 1
	select exclude_reason_cd, count(demo_user_id) from UNICA_TEMP.DE_FM_RALLY_TARGETING_EM_STG  group by 1
	

	SELECT RALLY_FLAG, SUM(POINTS), MAX(POINTS), MIN(POINTS) , MAX(PULL_DATE), count(distinct demo_user_id) FROM UNICA_TEMP.DE_FAMILY_MEN_RALLY_STG
	group by 1;
	
	
	sel count(demo_user_id) from UNICA_TEMP.DE_FM_RALLY_TARGETING_EM_STG
	where demo_user_id in (
176722949,
107493393,
199175982,
17676934,
845063476,
1229084683,
182212748,
114846791,
1157692775,
35929600,
927684273,
104517236,
1187848288,
165374832,
175863163,
51655605,
1057854418,
69588776,
178073211,
88617290,
287673190,
36413308,
696782356,
1115585042,
431019864,
67388821,
129084172,
118365892,
613669529
)  -- 29 users from blacklist