/*
CREATE MULTISET TABLE UNICA_TEMP.DE_FAMILY_MEN_STG ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      PRIMARY_USER_ID DECIMAL(18,0) NOT NULL,
      DEMO_USER_ID DECIMAL(18,0) NOT NULL,    
      SEGM_ID INTEGER NOT NULL,
	  AUD_ID INTEGER NOT NULL,
      USER_SITE_ID DECIMAL(4,0) NOT NULL,
	  TC VARCHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      COUPON VARCHAR(25) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      COUPON_CODE VARCHAR(25) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      EXP_DT VARCHAR(35) CHARACTER SET LATIN NOT CASESPECIFIC,
      EXCLUDE_REASON_CD SMALLINT)
PRIMARY INDEX ( PRIMARY_USER_ID ,SEGM_ID);
*/
--drop table UNICA_TEMP.DE_FAMILY_MEN_STG
DELETE FROM UNICA_TEMP.DE_FAMILY_MEN_STG ALL
;


INSERT INTO UNICA_TEMP.DE_FAMILY_MEN_STG

SELECT
	PII.PRMRY_USER_ID as PRIMARY_USER_ID,
	PII.DEMO_USER_ID,
	SEG.SEGM_ID,
	AUD.AUD_ID,
	PII.USER_SITE_ID,
	TC,
	COUPON,
	COUPON_CODE,
	TRIM(EXTRACT(DAY FROM END_TS)) || '.' || TRIM(EXTRACT(MONTH FROM END_TS)) || '.' || TRIM(EXTRACT(YEAR FROM END_TS)) AS EXP_DT,
	NULL AS EXCLUDE_REASON_CD
FROM
(SELECT
stg.USER_ID,
SEGMENT,
TC,
case when F.OFFER_STS_ID = 1 AND F.USED_CNT = 0 then 'ACTIVE' else 'REDEEMED' end as COUPON,
F.OFFER_CD as COUPON_CODE,
END_TS
FROM unica_temp.adobe_de_familymen_mam stg
 INNER JOIN PRS_RESTRICTED_V.EIP_LYLTY_OFFER F 
          ON     F.USER_ID=stg.USER_ID
  INNER JOIN PRS_RESTRICTED_V.EIP_LYLTY_CMPGN C 
          ON         F.LYLTY_CMPGN_ID = C.LYLTY_CMPGN_ID 
   INNER JOIN  PRS_RESTRICTED_V.EIP_CPN_DTL D 
          ON         D.INCNTV_CD = C.CMPGN_NAME 
WHERE 7=7
-- CHANGE MANHATTAN ID'S
          AND        F.LYLTY_CMPGN_ID IN (6342746701 )  --6342733801
		  
UNION ALL		  

SELECT
stg.USER_ID,
SEGMENT,
TC,
'CONTROL'  as COUPON,
'CONTROL' as COUPON_CODE,
current_date as END_TS
FROM unica_temp.adobe_de_familymen_mam stg
WHERE 7=7
AND TC='C'

UNION ALL		  

SELECT
stg.USER_ID,
'FAMILY_MEN' as SEGMENT,
'T' as TC,
'CONTROL'  as COUPON,
'CONTROL' as COUPON_CODE,
current_date as END_TS
FROM PRS_SECURE_V.MDM_USER_PII  stg
WHERE 7=7
AND  user_slctd_id in (
'marekmk', 
'dmalhao@ebay.com',
'psperling@ebay.de',  
'emnewman',
'steffisoleil84')
)  CPN
INNER JOIN PRS_SECURE_V.MDM_USER_PII AS PII on CPN.USER_ID=PII.USER_ID
INNER JOIN	UNICA_TEMP.XMP_AUDIENCE AS AUD
			ON	AUD.AUD_NAME = 'DE_FAMILY_MEN' AND
					77 = AUD.SITE_ID AND
					CURRENT_DATE BETWEEN AUD.START_DATE-10 AND AUD.END_DATE
		
		INNER JOIN	UNICA_TEMP.XMP_SEGMENT AS SEG
			ON	SEG.AUD_ID = AUD.AUD_ID AND
					SEG.SEGM_NAME IN ('FAMILY_MEN') AND
					CURRENT_DATE BETWEEN SEG.START_DATE-10 AND SEG.END_DATE
					;
					
			sel * from UNICA_TEMP.DE_FAMILY_MEN_STG;
	/*************************************************************************************************
* STANDARD SUPPRESSIONS, WATERFALL
**************************************************************************************************/

--USER SITE
UPDATE A 
FROM UNICA_TEMP.DE_FAMILY_MEN_STG AS A
SET EXCLUDE_REASON_CD =  5
WHERE 	EXCLUDE_REASON_CD IS NULL AND
			EXISTS	(
						SELECT *
						FROM PRS_SECURE_V.MDM_USER_PII AS PII
						WHERE
							A.DEMO_USER_ID = PII.USER_ID AND
							PII.USER_SITE_ID <> 77 AND
							 user_slctd_id not in (
'mogucan',  --Gybasova, Kristina
'marieck_6',  --Eckert, Thomas
'sraudschus', --Peijan, Stefanie
'emnewman', --Newman, Emma
'mllewiwa', --(Kristin Wyrwa)
'the9280', -- (Theresa Thüs)
'sa-32439' , --(Sandy Kim)
'kathihartung832',
'marekmk', 
'dmalhao@ebay.com',
'psperling@ebay.de',  
'steffisoleil84')
						)
;

--NON-CONFIRMED USERS
UPDATE A 
FROM UNICA_TEMP.DE_FAMILY_MEN_STG AS A
SET EXCLUDE_REASON_CD =  10
WHERE 	EXCLUDE_REASON_CD IS NULL AND
			EXISTS	(
						SELECT *
						FROM PRS_SECURE_V.MDM_USER_PII AS PII
						WHERE
							A.DEMO_USER_ID = PII.USER_ID AND
							PII.CNFRMD_YN = 'N'
						)
;

--GXO
UPDATE A 
FROM UNICA_TEMP.DE_FAMILY_MEN_STG AS A
SET EXCLUDE_REASON_CD =  15
WHERE 	EXCLUDE_REASON_CD IS NULL AND
			EXISTS	(
						SELECT *
						FROM PRS_SECURE_V.MDM_USER_PII AS PII
						WHERE 
							A.DEMO_USER_ID = PII.USER_ID AND
							PII.RGSTRD_YN = 'N'
						)
;

--BAD FEEDBACK
UPDATE A 
FROM UNICA_TEMP.DE_FAMILY_MEN_STG AS A
SET EXCLUDE_REASON_CD =  20
WHERE 	EXCLUDE_REASON_CD IS NULL AND
			EXISTS	(
						SELECT *
						FROM PRS_SECURE_V.MDM_USER_PII AS PII
						WHERE 
							A.DEMO_USER_ID = PII.USER_ID AND
							PII.FDBCK_YN = 'N'
						)
;

--CRM_GH FLAG
UPDATE A 
FROM UNICA_TEMP.DE_FAMILY_MEN_STG AS A
SET EXCLUDE_REASON_CD =  25
WHERE 	EXCLUDE_REASON_CD IS NULL AND
			EXISTS	(
						SELECT *
						FROM PRS_SECURE_V.MDM_USER_PII AS PII
						WHERE
							A.DEMO_USER_ID = PII.USER_ID AND
							PII.CRM_GH_YN = 'Y'
						)
;

--B2C
UPDATE A 
FROM UNICA_TEMP.DE_FAMILY_MEN_STG AS A
SET EXCLUDE_REASON_CD =  30
WHERE 	EXCLUDE_REASON_CD IS NULL AND
			EXISTS	(
						SELECT *
						FROM PRS_SECURE_V.MDM_USER_PII AS PII
						WHERE
							A.DEMO_USER_ID = PII.USER_ID AND
							PII.B2C_SLR_YN = 'Y'
						)
;			

--RISK
UPDATE A 
FROM UNICA_TEMP.DE_FAMILY_MEN_STG AS A
SET EXCLUDE_REASON_CD =  35
WHERE 	EXCLUDE_REASON_CD IS NULL AND
			EXISTS	(
						SELECT *
                        FROM access_views.dw_user_issue PII
						WHERE A.DEMO_USER_ID = PII.USER_ID AND
						scenario_id IN (1, 248, 250, 265, 491, 534, 535, 566, 629)
						AND status_id = 0		
						)
;

--NOT RAMPED  - provided list of 93 users plus one ID
UPDATE A 
FROM UNICA_TEMP.DE_FAMILY_MEN_STG AS A
SET EXCLUDE_REASON_CD =  40
WHERE 	EXCLUDE_REASON_CD IS NULL AND
			EXISTS	(
						SELECT *
						FROM p_dbm_input_t.DE_FAMILY_MEN_NOT_RAMPED2 AS PII
						WHERE
							A.DEMO_USER_ID = PII.USER_ID
													)
;			
			
--RSVP  - list of 1096 users
UPDATE A 
FROM UNICA_TEMP.DE_FAMILY_MEN_STG AS A
SET EXCLUDE_REASON_CD =  41
WHERE 	EXCLUDE_REASON_CD IS NULL AND
			EXISTS	(
						SELECT *
						FROM p_dbm_input_t.DE_FAMILY_MEN_RSVP_EXCL2 AS PII
						WHERE
							A.DEMO_USER_ID = PII.USER_ID
							and PII.user_id not in (
934807981,
1958416172,
1838431930,
1491835652,
1825895226,
866725528,
1284116821,
1556308855
)
													)
;			

--UNKNOWN - list of 1502 users
UPDATE A 
FROM UNICA_TEMP.DE_FAMILY_MEN_STG AS A
SET EXCLUDE_REASON_CD =  42
WHERE 	EXCLUDE_REASON_CD IS NULL AND
			EXISTS	(
						SELECT *
						FROM p_dbm_input_t.DE_FAMILY_MEN_UNK_EXCL2 AS PII
						WHERE
							A.DEMO_USER_ID = PII.USER_ID
													)
;			
								
drop table UNICA_TEMP.DE_FAMILY_MEN_DAILY;
CREATE MULTISET TABLE UNICA_TEMP.DE_FAMILY_MEN_DAILY as (
SELECT 
STG.PRIMARY_USER_ID,
STG.DEMO_USER_ID,    
STG.AUD_ID,
STG.SEGM_ID,
STG.TC,
STG.COUPON,
STG.COUPON_CODE,
STG.EXP_DT,
case when RWRD.user_id is null then 'N' else 'Y' end AS EBAY_PLUS,
RWRD.POINTS_CONFIRMED as POINTS_CONFIRMED,
RWRD.REWARDS_DATE as REWARDS_DATE,
case when MICRO.MICRO_CL_NAME is not null then  MICRO.MICRO_CL_NAME
else 'OTHERS' end as MICROSEGMENT
FROM UNICA_TEMP.DE_FAMILY_MEN_STG STG
LEFT JOIN (SELECT							A.USER_ID
											,SUM(OVRAL_POINTS_NUM) OVRAL_POINTS_NUM
											,SUM(CASE WHEN POINTS_CNFRMD_NUM <>0 THEN POINTS_CNFRMD_NUM ELSE 0 END) AS POINTS_CONFIRMED
											,SUM(CASE WHEN POINTS_PNDG_NUM <>0 THEN POINTS_PNDG_NUM ELSE 0 END) AS POINTS_PENDING
											,current_date-1 as REWARDS_DATE
						FROM								PRS_RESTRICTED_V.PLUS_RWRD_MBR A
						INNER JOIN								( SELECT				distinct BUYER_ID
																						,EBYPLS_BUYER_STATUS_CD
																						FROM access_views.EBYPLS_BUYER_SBSCRPTN_HIST 
																						WHERE SITE_ID = 77
																						and EBYPLS_BUYER_STATUS_CD in (0,1)
																						and current_date-2 between BUYER_STATUS_START_DT and BUYER_STATUS_END_DT
																						) PLUS
						ON										A.USER_ID = PLUS.BUYER_ID
						LEFT JOIN						PRS_RESTRICTED_V.PLUS_RWRD_POINTS_BLNC_HIST B
						ON										A.USER_ID = B.USER_ID
						WHERE							STATUS = 1
						AND									CURRENT_DATE BETWEEN A.STATUS_START_DT AND A.STATUS_END_DT
						GROUP BY						1 ) RWRD
ON STG.demo_user_id=RWRD.user_id
LEFT JOIN  (select user_id , MICRO_CL_NAME ,
RANK() OVER (PARTITION BY user_id  ORDER  BY user_id,user_cl_order  ASC ) AS ITEM_ORDER
from PRS_RESTRICTED_V.MICRO_CLSTR_USER_SGMNT MICRO
where 7=7 and MICRO.SITE_ID=77
and data_dt = (select max(data_dt) from  PRS_RESTRICTED_V.MICRO_CLSTR_USER_SGMNT where SITE_ID=77)
and MICRO_CL_ID IN (15,1,10,17)
QUALIFY ITEM_ORDER = 1) MICRO
ON  STG.demo_user_id=MICRO.user_id 
WHERE 	STG.EXCLUDE_REASON_CD IS NULL

) WITH DATA;
/*************************************************************************************************
MESSAGE LEVEL - START WITH HERO MESSAGES
Taking data from Audience, populating message staging table
***************************************************************************************************/

DELETE FROM UNICA_TEMP.DE_FM_MESSAGE_DAILY_STG ALL
;

INSERT INTO UNICA_TEMP.DE_FM_MESSAGE_DAILY_STG
SELECT
      AUD.PRIMARY_USER_ID,
      AUD.DEMO_USER_ID,    
	AUD.AUD_ID,
	AUD.SEGM_ID,
	MSG.MSG_ID,
	NULL as JOURNEY_ID,
	NULL as SEQUENCE,	
	MSG.PRIORITY,
	NULL AS EXCL_GRP_ID,
	NULL AS EM_CHANNEL,
	NULL AS MC_CHANNEL,
	NULL AS OM_CHANNEL,
	NULL AS PN_CHANNEL,
	NULL AS HERO_MESSAGE_YN,
	NULL AS MESSAGE2_YN,
	NULL AS MESSAGE3_YN,
	NULL AS MESSAGE4_YN,
	NULL AS MESSAGE5_YN,
	NULL AS MESSAGE6_YN,
	NULL AS EXCLUDE_REASON_CD,
	CAST (CURRENT_DATE AS DATE FORMAT 'YYYY-MM-DD') AS DATA_DATE
FROM
	UNICA_TEMP.DE_FAMILY_MEN_DAILY AS AUD
	
		INNER JOIN UNICA_TEMP.XMP_MAP_SEGMENT_MESSAGE AS MAP_SM
			ON	AUD.SEGM_ID = MAP_SM.SEGM_ID AND
					CURRENT_DATE BETWEEN MAP_SM.START_DATE-10 AND MAP_SM.END_DATE
					
		INNER JOIN UNICA_TEMP.XMP_MESSAGE AS MSG
			ON	MSG.MSG_ID = MAP_SM.MSG_ID AND
					CURRENT_DATE BETWEEN MSG.START_DATE-10 AND MSG.END_DATE AND
					MSG.MSG_NAME = 'DE_FM001_MAIN'	
;

INSERT INTO UNICA_TEMP.DE_FM_MESSAGE_DAILY_STG
SELECT
      AUD.PRIMARY_USER_ID,
      AUD.DEMO_USER_ID,    
	AUD.AUD_ID,
	AUD.SEGM_ID,
	MSG.MSG_ID,
	NULL as JOURNEY_ID,
	NULL as SEQUENCE,	
	MSG.PRIORITY,
	NULL AS EXCL_GRP_ID,
	NULL AS EM_CHANNEL,
	NULL AS MC_CHANNEL,
	NULL AS OM_CHANNEL,
	NULL AS PN_CHANNEL,
	NULL AS HERO_MESSAGE_YN,
	NULL AS MESSAGE2_YN,
	NULL AS MESSAGE3_YN,
	NULL AS MESSAGE4_YN,
	NULL AS MESSAGE5_YN,
	NULL AS MESSAGE6_YN,
	NULL AS EXCLUDE_REASON_CD,
	CAST (CURRENT_DATE AS DATE FORMAT 'YYYY-MM-DD') AS DATA_DATE
FROM
	UNICA_TEMP.DE_FAMILY_MEN_DAILY AS AUD
	
		INNER JOIN UNICA_TEMP.XMP_MAP_SEGMENT_MESSAGE AS MAP_SM
			ON	AUD.SEGM_ID = MAP_SM.SEGM_ID AND
					CURRENT_DATE BETWEEN MAP_SM.START_DATE-10 AND MAP_SM.END_DATE
					
		INNER JOIN UNICA_TEMP.XMP_MESSAGE AS MSG
			ON	MSG.MSG_ID = MAP_SM.MSG_ID AND
					CURRENT_DATE BETWEEN MSG.START_DATE-10 AND MSG.END_DATE AND
					MSG.MSG_NAME = 'DE_FM002_REW_NO'	
	WHERE (current_date<= CAST('10/11/2019' as date FORMAT 'MM/DD/YYYY')	OR 		EBAY_PLUS='N'	)
;

INSERT INTO UNICA_TEMP.DE_FM_MESSAGE_DAILY_STG
SELECT
      AUD.PRIMARY_USER_ID,
      AUD.DEMO_USER_ID,    
	AUD.AUD_ID,
	AUD.SEGM_ID,
	MSG.MSG_ID,
	NULL as JOURNEY_ID,
	NULL as SEQUENCE,	
	MSG.PRIORITY,
	NULL AS EXCL_GRP_ID,
	NULL AS EM_CHANNEL,
	NULL AS MC_CHANNEL,
	NULL AS OM_CHANNEL,
	NULL AS PN_CHANNEL,
	NULL AS HERO_MESSAGE_YN,
	NULL AS MESSAGE2_YN,
	NULL AS MESSAGE3_YN,
	NULL AS MESSAGE4_YN,
	NULL AS MESSAGE5_YN,
	NULL AS MESSAGE6_YN,
	NULL AS EXCLUDE_REASON_CD,
	CAST (CURRENT_DATE AS DATE FORMAT 'YYYY-MM-DD') AS DATA_DATE
FROM
	UNICA_TEMP.DE_FAMILY_MEN_DAILY AS AUD
	
		INNER JOIN UNICA_TEMP.XMP_MAP_SEGMENT_MESSAGE AS MAP_SM
			ON	AUD.SEGM_ID = MAP_SM.SEGM_ID AND
					CURRENT_DATE BETWEEN MAP_SM.START_DATE-10 AND MAP_SM.END_DATE
					
		INNER JOIN UNICA_TEMP.XMP_MESSAGE AS MSG
			ON	MSG.MSG_ID = MAP_SM.MSG_ID AND
					CURRENT_DATE BETWEEN MSG.START_DATE-10 AND MSG.END_DATE AND
					MSG.MSG_NAME = 'DE_FM003_REW_YES_BELOW200'	
	WHERE 7=7
	AND current_date> CAST('10/11/2019' as date FORMAT 'MM/DD/YYYY')	
	AND ebay_plus='Y'
	AND NVL(POINTS_CONFIRMED,0)<200
;

INSERT INTO UNICA_TEMP.DE_FM_MESSAGE_DAILY_STG
SELECT
      AUD.PRIMARY_USER_ID,
      AUD.DEMO_USER_ID,    
	AUD.AUD_ID,
	AUD.SEGM_ID,
	MSG.MSG_ID,
	NULL as JOURNEY_ID,
	NULL as SEQUENCE,	
	MSG.PRIORITY,
	NULL AS EXCL_GRP_ID,
	NULL AS EM_CHANNEL,
	NULL AS MC_CHANNEL,
	NULL AS OM_CHANNEL,
	NULL AS PN_CHANNEL,
	NULL AS HERO_MESSAGE_YN,
	NULL AS MESSAGE2_YN,
	NULL AS MESSAGE3_YN,
	NULL AS MESSAGE4_YN,
	NULL AS MESSAGE5_YN,
	NULL AS MESSAGE6_YN,
	NULL AS EXCLUDE_REASON_CD,
	CAST (CURRENT_DATE AS DATE FORMAT 'YYYY-MM-DD') AS DATA_DATE
FROM
	UNICA_TEMP.DE_FAMILY_MEN_DAILY AS AUD
	
		INNER JOIN UNICA_TEMP.XMP_MAP_SEGMENT_MESSAGE AS MAP_SM
			ON	AUD.SEGM_ID = MAP_SM.SEGM_ID AND
					CURRENT_DATE BETWEEN MAP_SM.START_DATE-10 AND MAP_SM.END_DATE
					
		INNER JOIN UNICA_TEMP.XMP_MESSAGE AS MSG
			ON	MSG.MSG_ID = MAP_SM.MSG_ID AND
					CURRENT_DATE BETWEEN MSG.START_DATE-10 AND MSG.END_DATE AND
					MSG.MSG_NAME = 'DE_FM004_REW_YES_ABOVE200'	
	WHERE 7=7
	AND current_date> CAST('10/11/2019' as date FORMAT 'MM/DD/YYYY')	
	AND ebay_plus='Y'
	AND NVL(POINTS_CONFIRMED,0)>=200
;

INSERT INTO UNICA_TEMP.DE_FM_MESSAGE_DAILY_STG
SELECT
      AUD.PRIMARY_USER_ID,
      AUD.DEMO_USER_ID,    
	AUD.AUD_ID,
	AUD.SEGM_ID,
	MSG.MSG_ID,
	NULL as JOURNEY_ID,
	NULL as SEQUENCE,	
	MSG.PRIORITY,
	NULL AS EXCL_GRP_ID,
	NULL AS EM_CHANNEL,
	NULL AS MC_CHANNEL,
	NULL AS OM_CHANNEL,
	NULL AS PN_CHANNEL,
	NULL AS HERO_MESSAGE_YN,
	NULL AS MESSAGE2_YN,
	NULL AS MESSAGE3_YN,
	NULL AS MESSAGE4_YN,
	NULL AS MESSAGE5_YN,
	NULL AS MESSAGE6_YN,
	NULL AS EXCLUDE_REASON_CD,
	CAST (CURRENT_DATE AS DATE FORMAT 'YYYY-MM-DD') AS DATA_DATE
FROM
	UNICA_TEMP.DE_FAMILY_MEN_DAILY AS AUD
	
		INNER JOIN UNICA_TEMP.XMP_MAP_SEGMENT_MESSAGE AS MAP_SM
			ON	AUD.SEGM_ID = MAP_SM.SEGM_ID AND
					CURRENT_DATE BETWEEN MAP_SM.START_DATE-10 AND MAP_SM.END_DATE
					
		INNER JOIN UNICA_TEMP.XMP_MESSAGE AS MSG
			ON	MSG.MSG_ID = MAP_SM.MSG_ID AND
					CURRENT_DATE BETWEEN MSG.START_DATE-10 AND MSG.END_DATE AND
					MSG.MSG_NAME = 'DE_FM005_SPEND_STRETCH'	
	WHERE 7=7
	and TC='T'
	AND COUPON='ACTIVE'
;

INSERT INTO UNICA_TEMP.DE_FM_MESSAGE_DAILY_STG
SELECT
      AUD.PRIMARY_USER_ID,
      AUD.DEMO_USER_ID,    
	AUD.AUD_ID,
	AUD.SEGM_ID,
	MSG.MSG_ID,
	NULL as JOURNEY_ID,
	NULL as SEQUENCE,	
	MSG.PRIORITY,
	NULL AS EXCL_GRP_ID,
	NULL AS EM_CHANNEL,
	NULL AS MC_CHANNEL,
	NULL AS OM_CHANNEL,
	NULL AS PN_CHANNEL,
	NULL AS HERO_MESSAGE_YN,
	NULL AS MESSAGE2_YN,
	NULL AS MESSAGE3_YN,
	NULL AS MESSAGE4_YN,
	NULL AS MESSAGE5_YN,
	NULL AS MESSAGE6_YN,
	NULL AS EXCLUDE_REASON_CD,
	CAST (CURRENT_DATE AS DATE FORMAT 'YYYY-MM-DD') AS DATA_DATE
FROM
	UNICA_TEMP.DE_FAMILY_MEN_DAILY AS AUD
	
		INNER JOIN UNICA_TEMP.XMP_MAP_SEGMENT_MESSAGE AS MAP_SM
			ON	AUD.SEGM_ID = MAP_SM.SEGM_ID AND
					CURRENT_DATE BETWEEN MAP_SM.START_DATE-10 AND MAP_SM.END_DATE
					
		INNER JOIN UNICA_TEMP.XMP_MESSAGE AS MSG
			ON	MSG.MSG_ID = MAP_SM.MSG_ID AND
					CURRENT_DATE BETWEEN MSG.START_DATE-10 AND MSG.END_DATE AND
					MSG.MSG_NAME = 'DE_FM006_INVENTORY_PLUS'	
	WHERE 7=7
	AND (current_date< CAST('11/01/2019' as date FORMAT 'MM/DD/YYYY')	OR
	(current_date> CAST('11/01/2019' as date FORMAT 'MM/DD/YYYY')	
	AND  EXTRACT(DAY FROM current_date) MOD 2 =1))
	
	
;

INSERT INTO UNICA_TEMP.DE_FM_MESSAGE_DAILY_STG
SELECT
      AUD.PRIMARY_USER_ID,
      AUD.DEMO_USER_ID,    
	AUD.AUD_ID,
	AUD.SEGM_ID,
	MSG.MSG_ID,
	NULL as JOURNEY_ID,
	NULL as SEQUENCE,	
	MSG.PRIORITY,
	NULL AS EXCL_GRP_ID,
	NULL AS EM_CHANNEL,
	NULL AS MC_CHANNEL,
	NULL AS OM_CHANNEL,
	NULL AS PN_CHANNEL,
	NULL AS HERO_MESSAGE_YN,
	NULL AS MESSAGE2_YN,
	NULL AS MESSAGE3_YN,
	NULL AS MESSAGE4_YN,
	NULL AS MESSAGE5_YN,
	NULL AS MESSAGE6_YN,
	NULL AS EXCLUDE_REASON_CD,
	CAST (CURRENT_DATE AS DATE FORMAT 'YYYY-MM-DD') AS DATA_DATE
FROM
	UNICA_TEMP.DE_FAMILY_MEN_DAILY AS AUD
	
		INNER JOIN UNICA_TEMP.XMP_MAP_SEGMENT_MESSAGE AS MAP_SM
			ON	AUD.SEGM_ID = MAP_SM.SEGM_ID AND
					CURRENT_DATE BETWEEN MAP_SM.START_DATE-10 AND MAP_SM.END_DATE
					
		INNER JOIN UNICA_TEMP.XMP_MESSAGE AS MSG
			ON	MSG.MSG_ID = MAP_SM.MSG_ID AND
					CURRENT_DATE BETWEEN MSG.START_DATE-10 AND MSG.END_DATE AND
					MSG.MSG_NAME = 'DE_FM007_INVENTORY_EVERYDAY'	
	WHERE 7=7
	AND current_date> CAST('11/01/2019' as date FORMAT 'MM/DD/YYYY')	
	AND  EXTRACT(DAY FROM current_date) MOD 2 =0
;

INSERT INTO UNICA_TEMP.DE_FM_MESSAGE_DAILY_STG
SELECT
      AUD.PRIMARY_USER_ID,
      AUD.DEMO_USER_ID,    
	AUD.AUD_ID,
	AUD.SEGM_ID,
	MSG.MSG_ID,
	NULL as JOURNEY_ID,
	NULL as SEQUENCE,	
	MSG.PRIORITY,
	NULL AS EXCL_GRP_ID,
	NULL AS EM_CHANNEL,
	NULL AS MC_CHANNEL,
	NULL AS OM_CHANNEL,
	NULL AS PN_CHANNEL,
	NULL AS HERO_MESSAGE_YN,
	NULL AS MESSAGE2_YN,
	NULL AS MESSAGE3_YN,
	NULL AS MESSAGE4_YN,
	NULL AS MESSAGE5_YN,
	NULL AS MESSAGE6_YN,
	NULL AS EXCLUDE_REASON_CD,
	CAST (CURRENT_DATE AS DATE FORMAT 'YYYY-MM-DD') AS DATA_DATE
FROM
	UNICA_TEMP.DE_FAMILY_MEN_DAILY AS AUD
	
		INNER JOIN UNICA_TEMP.XMP_MAP_SEGMENT_MESSAGE AS MAP_SM
			ON	AUD.SEGM_ID = MAP_SM.SEGM_ID AND
					CURRENT_DATE BETWEEN MAP_SM.START_DATE-10 AND MAP_SM.END_DATE
					
		INNER JOIN UNICA_TEMP.XMP_MESSAGE AS MSG
			ON	MSG.MSG_ID = MAP_SM.MSG_ID AND
					CURRENT_DATE BETWEEN MSG.START_DATE-10 AND MSG.END_DATE AND
					MSG.MSG_NAME = 'DE_FM008_MICRO_CAR_PARTS'	
	WHERE 7=7
	AND MICROSEGMENT = 'Car & Motorbike parts'
;

INSERT INTO UNICA_TEMP.DE_FM_MESSAGE_DAILY_STG
SELECT
      AUD.PRIMARY_USER_ID,
      AUD.DEMO_USER_ID,    
	AUD.AUD_ID,
	AUD.SEGM_ID,
	MSG.MSG_ID,
	NULL as JOURNEY_ID,
	NULL as SEQUENCE,	
	MSG.PRIORITY,
	NULL AS EXCL_GRP_ID,
	NULL AS EM_CHANNEL,
	NULL AS MC_CHANNEL,
	NULL AS OM_CHANNEL,
	NULL AS PN_CHANNEL,
	NULL AS HERO_MESSAGE_YN,
	NULL AS MESSAGE2_YN,
	NULL AS MESSAGE3_YN,
	NULL AS MESSAGE4_YN,
	NULL AS MESSAGE5_YN,
	NULL AS MESSAGE6_YN,
	NULL AS EXCLUDE_REASON_CD,
	CAST (CURRENT_DATE AS DATE FORMAT 'YYYY-MM-DD') AS DATA_DATE
FROM
	UNICA_TEMP.DE_FAMILY_MEN_DAILY AS AUD
	
		INNER JOIN UNICA_TEMP.XMP_MAP_SEGMENT_MESSAGE AS MAP_SM
			ON	AUD.SEGM_ID = MAP_SM.SEGM_ID AND
					CURRENT_DATE BETWEEN MAP_SM.START_DATE-10 AND MAP_SM.END_DATE
					
		INNER JOIN UNICA_TEMP.XMP_MESSAGE AS MSG
			ON	MSG.MSG_ID = MAP_SM.MSG_ID AND
					CURRENT_DATE BETWEEN MSG.START_DATE-10 AND MSG.END_DATE AND
					MSG.MSG_NAME = 'DE_FM009_MICRO_HOME_GARDEN'	
	WHERE 7=7
	AND MICROSEGMENT = 'Home Improver & Garden'
;

INSERT INTO UNICA_TEMP.DE_FM_MESSAGE_DAILY_STG
SELECT
      AUD.PRIMARY_USER_ID,
      AUD.DEMO_USER_ID,    
	AUD.AUD_ID,
	AUD.SEGM_ID,
	MSG.MSG_ID,
	NULL as JOURNEY_ID,
	NULL as SEQUENCE,	
	MSG.PRIORITY,
	NULL AS EXCL_GRP_ID,
	NULL AS EM_CHANNEL,
	NULL AS MC_CHANNEL,
	NULL AS OM_CHANNEL,
	NULL AS PN_CHANNEL,
	NULL AS HERO_MESSAGE_YN,
	NULL AS MESSAGE2_YN,
	NULL AS MESSAGE3_YN,
	NULL AS MESSAGE4_YN,
	NULL AS MESSAGE5_YN,
	NULL AS MESSAGE6_YN,
	NULL AS EXCLUDE_REASON_CD,
	CAST (CURRENT_DATE AS DATE FORMAT 'YYYY-MM-DD') AS DATA_DATE
FROM
	UNICA_TEMP.DE_FAMILY_MEN_DAILY AS AUD
	
		INNER JOIN UNICA_TEMP.XMP_MAP_SEGMENT_MESSAGE AS MAP_SM
			ON	AUD.SEGM_ID = MAP_SM.SEGM_ID AND
					CURRENT_DATE BETWEEN MAP_SM.START_DATE-10 AND MAP_SM.END_DATE
					
		INNER JOIN UNICA_TEMP.XMP_MESSAGE AS MSG
			ON	MSG.MSG_ID = MAP_SM.MSG_ID AND
					CURRENT_DATE BETWEEN MSG.START_DATE-10 AND MSG.END_DATE AND
					MSG.MSG_NAME = 'DE_FM010_MICRO_ELECTRONICS'	
	WHERE 7=7
	AND MICROSEGMENT = 'Consumer Electronics & Mobile'
;

INSERT INTO UNICA_TEMP.DE_FM_MESSAGE_DAILY_STG
SELECT
      AUD.PRIMARY_USER_ID,
      AUD.DEMO_USER_ID,    
	AUD.AUD_ID,
	AUD.SEGM_ID,
	MSG.MSG_ID,
	NULL as JOURNEY_ID,
	NULL as SEQUENCE,	
	MSG.PRIORITY,
	NULL AS EXCL_GRP_ID,
	NULL AS EM_CHANNEL,
	NULL AS MC_CHANNEL,
	NULL AS OM_CHANNEL,
	NULL AS PN_CHANNEL,
	NULL AS HERO_MESSAGE_YN,
	NULL AS MESSAGE2_YN,
	NULL AS MESSAGE3_YN,
	NULL AS MESSAGE4_YN,
	NULL AS MESSAGE5_YN,
	NULL AS MESSAGE6_YN,
	NULL AS EXCLUDE_REASON_CD,
	CAST (CURRENT_DATE AS DATE FORMAT 'YYYY-MM-DD') AS DATA_DATE
FROM
	UNICA_TEMP.DE_FAMILY_MEN_DAILY AS AUD
	
		INNER JOIN UNICA_TEMP.XMP_MAP_SEGMENT_MESSAGE AS MAP_SM
			ON	AUD.SEGM_ID = MAP_SM.SEGM_ID AND
					CURRENT_DATE BETWEEN MAP_SM.START_DATE-10 AND MAP_SM.END_DATE
					
		INNER JOIN UNICA_TEMP.XMP_MESSAGE AS MSG
			ON	MSG.MSG_ID = MAP_SM.MSG_ID AND
					CURRENT_DATE BETWEEN MSG.START_DATE-10 AND MSG.END_DATE AND
					MSG.MSG_NAME = 'DE_FM013_MICRO_KIDS'	
	WHERE 7=7
	AND MICROSEGMENT = 'Kids & Babies'
;

INSERT INTO UNICA_TEMP.DE_FM_MESSAGE_DAILY_STG
SELECT
      AUD.PRIMARY_USER_ID,
      AUD.DEMO_USER_ID,    
	AUD.AUD_ID,
	AUD.SEGM_ID,
	MSG.MSG_ID,
	NULL as JOURNEY_ID,
	NULL as SEQUENCE,	
	MSG.PRIORITY,
	NULL AS EXCL_GRP_ID,
	NULL AS EM_CHANNEL,
	NULL AS MC_CHANNEL,
	NULL AS OM_CHANNEL,
	NULL AS PN_CHANNEL,
	NULL AS HERO_MESSAGE_YN,
	NULL AS MESSAGE2_YN,
	NULL AS MESSAGE3_YN,
	NULL AS MESSAGE4_YN,
	NULL AS MESSAGE5_YN,
	NULL AS MESSAGE6_YN,
	NULL AS EXCLUDE_REASON_CD,
	CAST (CURRENT_DATE AS DATE FORMAT 'YYYY-MM-DD') AS DATA_DATE
FROM
	UNICA_TEMP.DE_FAMILY_MEN_DAILY AS AUD
	
		INNER JOIN UNICA_TEMP.XMP_MAP_SEGMENT_MESSAGE AS MAP_SM
			ON	AUD.SEGM_ID = MAP_SM.SEGM_ID AND
					CURRENT_DATE BETWEEN MAP_SM.START_DATE-10 AND MAP_SM.END_DATE
					
		INNER JOIN  UNICA_TEMP.XMP_MESSAGE AS MSG
			ON	MSG.MSG_ID = MAP_SM.MSG_ID AND
					CURRENT_DATE BETWEEN MSG.START_DATE-10 AND MSG.END_DATE AND
					MSG.MSG_NAME = 'DE_FM011_MIRO_FALLBACK'	
	WHERE 7=7
	AND MICROSEGMENT = 'OTHERS'
;

INSERT INTO UNICA_TEMP.DE_FM_MESSAGE_DAILY_STG
SELECT
      AUD.PRIMARY_USER_ID,
      AUD.DEMO_USER_ID,    
	AUD.AUD_ID,
	AUD.SEGM_ID,
	MSG.MSG_ID,
	NULL as JOURNEY_ID,
	NULL as SEQUENCE,	
	MSG.PRIORITY,
	NULL AS EXCL_GRP_ID,
	NULL AS EM_CHANNEL,
	NULL AS MC_CHANNEL,
	NULL AS OM_CHANNEL,
	NULL AS PN_CHANNEL,
	NULL AS HERO_MESSAGE_YN,
	NULL AS MESSAGE2_YN,
	NULL AS MESSAGE3_YN,
	NULL AS MESSAGE4_YN,
	NULL AS MESSAGE5_YN,
	NULL AS MESSAGE6_YN,
	NULL AS EXCLUDE_REASON_CD,
	CAST (CURRENT_DATE AS DATE FORMAT 'YYYY-MM-DD') AS DATA_DATE
FROM
	UNICA_TEMP.DE_FAMILY_MEN_DAILY AS AUD
	
		INNER JOIN UNICA_TEMP.XMP_MAP_SEGMENT_MESSAGE AS MAP_SM
			ON	AUD.SEGM_ID = MAP_SM.SEGM_ID AND
					CURRENT_DATE BETWEEN MAP_SM.START_DATE-10 AND MAP_SM.END_DATE
					
		INNER JOIN UNICA_TEMP.XMP_MESSAGE AS MSG
			ON	MSG.MSG_ID = MAP_SM.MSG_ID AND
					CURRENT_DATE BETWEEN MSG.START_DATE-10 AND MSG.END_DATE AND
					MSG.MSG_NAME = 'DE_FM012_EBAY_PLUS'	
	WHERE 7=7
;

UPDATE	UNICA_TEMP.DE_FM_MESSAGE_DAILY_STG
FROM 	UNICA_TEMP.DE_FM_MESSAGE_PLACEMENT AS PLAC
SET
	HERO_MESSAGE_YN = PLAC.HERO_MESSAGE_YN,
	MESSAGE2_YN = PLAC.MESSAGE2_YN,
	MESSAGE3_YN = PLAC.MESSAGE3_YN,
	MESSAGE4_YN = PLAC.MESSAGE4_YN,
	MESSAGE5_YN = PLAC.MESSAGE5_YN,
	MESSAGE6_YN = PLAC.MESSAGE6_YN
WHERE UNICA_TEMP.DE_FM_MESSAGE_DAILY_STG.MSG_ID = PLAC.MSG_ID
;

/*UPDATE CHANNELS*/
UPDATE	UNICA_TEMP.DE_FM_MESSAGE_DAILY_STG
FROM		UNICA_TEMP.XMP_MESSAGE_CHANNEL AS CHNL
SET
	EM_CHANNEL = CHNL.EM_CHANNEL,
	MC_CHANNEL = CHNL.MC_CHANNEL,
	OM_CHANNEL = CHNL.OM_CHANNEL,
	PN_CHANNEL = CHNL.PN_CHANNEL
WHERE UNICA_TEMP.DE_FM_MESSAGE_DAILY_STG.MSG_ID = CHNL.MSG_ID
;
/*EXCLUDE USERS WHO DON'T HAVE ENOUGH MESSAGES*/
UPDATE	UNICA_TEMP.DE_FM_MESSAGE_DAILY_STG
FROM		(
				SELECT PRIMARY_USER_ID,AUD_ID,SEGM_ID, COUNT(*) AS USR_CNT
				FROM UNICA_TEMP.DE_FM_MESSAGE_DAILY_STG
				GROUP BY 1,2,3
				HAVING USR_CNT < 5
				) AS EXC
SET	EXCLUDE_REASON_CD = 44
WHERE
	UNICA_TEMP.DE_FM_MESSAGE_DAILY_STG.PRIMARY_USER_ID = EXC.PRIMARY_USER_ID AND
	UNICA_TEMP.DE_FM_MESSAGE_DAILY_STG.AUD_ID = EXC.AUD_ID AND
	UNICA_TEMP.DE_FM_MESSAGE_DAILY_STG.SEGM_ID = EXC.SEGM_ID 
;
--sel * from UNICA_TEMP.DE_FM_MESSAGE_DAILY_STG

 /*************************************************************************************************
INSERTING INTO EMAIL STAGING TABLE
***************************************************************************************************/
	
DELETE FROM UNICA_TEMP.DE_FM_TARGETING_DAILY_EM_STG ALL;
 
 INSERT INTO UNICA_TEMP.DE_FM_TARGETING_DAILY_EM_STG
 SELECT
	STG.PRIMARY_USER_ID,
	STG.DEMO_USER_ID,
	STG.AUD_ID,
	STG.SEGM_ID,
	STG.JOURNEY_ID AS JOURNEY_ID,
	STG.SEQUENCE AS SEQUENCE,
	STG.MSG_ID AS HERO_MESSAGE,
	NULL AS MESSAGE2,
	NULL AS MESSAGE3,
	NULL AS MESSAGE4,
	NULL AS MESSAGE5,
	NULL AS MESSAGE6,
	NULL AS EXCLUDE_REASON_CD,
	NVL(POINTS_CONFIRMED,0)  as PLUS_POINTS,
	REWARDS_DATE as REWARDS_DATE,
	'N' as CH_MC_YN,
	STG.DATA_DATE	
FROM
	UNICA_TEMP.DE_FM_MESSAGE_DAILY_STG STG
	JOIN  UNICA_TEMP.DE_FAMILY_MEN_DAILY DAILY on STG.DEMO_USER_ID=DAILY.DEMO_USER_ID
WHERE
	EXCLUDE_REASON_CD IS NULL AND
	HERO_MESSAGE_YN = 'Y'
GROUP BY
	STG.PRIMARY_USER_ID,
	STG.DEMO_USER_ID,
	STG.AUD_ID,
	STG.SEGM_ID,
	STG.JOURNEY_ID,
	STG.SEQUENCE,
	STG.MSG_ID,
	POINTS_CONFIRMED,
	REWARDS_DATE,
	STG.DATA_DATE
;	

UPDATE UNICA_TEMP.DE_FM_TARGETING_DAILY_EM_STG
FROM UNICA_TEMP.DE_FM_MESSAGE_DAILY_STG AS B
 SET 
	MESSAGE2=B.MSG_ID
WHERE
	UNICA_TEMP.DE_FM_TARGETING_DAILY_EM_STG.PRIMARY_USER_ID = B.PRIMARY_USER_ID AND
	B.MESSAGE2_YN = 'Y' AND
	B.EXCLUDE_REASON_CD IS NULL
;

UPDATE UNICA_TEMP.DE_FM_TARGETING_DAILY_EM_STG
FROM UNICA_TEMP.DE_FM_MESSAGE_DAILY_STG AS B
 SET 
	MESSAGE3=B.MSG_ID
WHERE
	UNICA_TEMP.DE_FM_TARGETING_DAILY_EM_STG.PRIMARY_USER_ID = B.PRIMARY_USER_ID AND
	B.MESSAGE3_YN = 'Y'
;

UPDATE UNICA_TEMP.DE_FM_TARGETING_DAILY_EM_STG
FROM UNICA_TEMP.DE_FM_MESSAGE_DAILY_STG AS B
 SET 
	MESSAGE4=B.MSG_ID
WHERE
	UNICA_TEMP.DE_FM_TARGETING_DAILY_EM_STG.PRIMARY_USER_ID = B.PRIMARY_USER_ID AND
	B.MESSAGE4_YN = 'Y'
;

UPDATE UNICA_TEMP.DE_FM_TARGETING_DAILY_EM_STG
FROM UNICA_TEMP.DE_FM_MESSAGE_DAILY_STG AS B
 SET 
	MESSAGE5=B.MSG_ID
WHERE
	UNICA_TEMP.DE_FM_TARGETING_DAILY_EM_STG.PRIMARY_USER_ID = B.PRIMARY_USER_ID AND
	B.MESSAGE5_YN = 'Y'
;

UPDATE UNICA_TEMP.DE_FM_TARGETING_DAILY_EM_STG
FROM UNICA_TEMP.DE_FM_MESSAGE_DAILY_STG AS B
 SET 
	MESSAGE6=B.MSG_ID
WHERE
	UNICA_TEMP.DE_FM_TARGETING_DAILY_EM_STG.PRIMARY_USER_ID = B.PRIMARY_USER_ID AND
	B.MESSAGE6_YN = 'Y'
;




--MC FLAG
UPDATE A FROM UNICA_TEMP.DE_FM_TARGETING_DAILY_EM_STG AS A
SET
	CH_MC_YN =  'Y'
	
WHERE 	CH_MC_YN =  'N' AND
			EXISTS	(
						SELECT *
						FROM PRS_SECURE_V.MDM_USER_PII AS PII
						WHERE (PII.MSGCENTER_PROMOSOFFERSEVENTS = 'Y'   
						or user_slctd_id  in (
'mogucan',  --Gybasova, Kristina
'marieck_6',  --Eckert, Thomas
'sraudschus', --Peijan, Stefanie
'emnewman', --Newman, Emma
'mllewiwa', --(Kristin Wyrwa)
'the9280', -- (Theresa Thüs)
'sa-32439' , --(Sandy Kim)
'kathihartung832',
'marekmk', 
'dmalhao@ebay.com',
'psperling@ebay.de',  
'steffisoleil84'))
						AND A.DEMO_USER_ID = PII.USER_ID
						)
;

--NON-RESPONDER FLAG
UPDATE A FROM UNICA_TEMP.DE_FM_TARGETING_DAILY_EM_STG AS A
SET
	EXCLUDE_REASON_CD =  45
	
WHERE 	EXCLUDE_REASON_CD IS NULL AND
			EXISTS	(
						SELECT *
						FROM PRS_SECURE_V.MDM_USER_PII AS PII
						WHERE PII.RSPNDR_YN = 'N' AND A.DEMO_USER_ID = PII.USER_ID
						)
;
						
--BLACKLIST FLAG
UPDATE A FROM UNICA_TEMP.DE_FM_TARGETING_DAILY_EM_STG AS A
SET
	EXCLUDE_REASON_CD =  50
	
WHERE 	EXCLUDE_REASON_CD IS NULL AND
			EXISTS	(
						SELECT *
						FROM PRS_SECURE_V.MDM_USER_PII AS PII
						WHERE PII.BLCKLST_YN = 'Y' AND A.DEMO_USER_ID = PII.USER_ID
						)
;
						
--UNDELIVERABLE FLAG
UPDATE A FROM UNICA_TEMP.DE_FM_TARGETING_DAILY_EM_STG AS A
SET
	EXCLUDE_REASON_CD =  55
	
WHERE 	EXCLUDE_REASON_CD IS NULL AND
			EXISTS	(
						SELECT *
						FROM PRS_SECURE_V.MDM_USER_PII AS PII
						WHERE PII.DLVRABLE_YN = 'N' AND A.DEMO_USER_ID = PII.USER_ID
						and user_slctd_id not in (
'mogucan',  --Gybasova, Kristina
'marieck_6',  --Eckert, Thomas
'sraudschus', --Peijan, Stefanie
'emnewman', --Newman, Emma
'mllewiwa', --(Kristin Wyrwa)
'the9280', -- (Theresa Thüs)
'sa-32439' , --(Sandy Kim)
'kathihartung832',
'marekmk', 
'dmalhao@ebay.com',
'psperling@ebay.de',  
'steffisoleil84')
						)
;

--ACTIVITY FLAG
UPDATE A FROM UNICA_TEMP.DE_FM_TARGETING_DAILY_EM_STG AS A
SET
	EXCLUDE_REASON_CD =  60
	
WHERE 	EXCLUDE_REASON_CD IS NULL AND
			EXISTS	(
						SELECT *
						FROM PRS_SECURE_V.MDM_USER_PII AS PII
						WHERE PII.ACTV_YN = 'N' AND A.DEMO_USER_ID = PII.USER_ID
						)
;
						
--EMAIL MASTER PREFERENCE FLAG
UPDATE A FROM UNICA_TEMP.DE_FM_TARGETING_DAILY_EM_STG AS A
SET
	EXCLUDE_REASON_CD =  65
	
WHERE 	EXCLUDE_REASON_CD IS NULL AND
			EXISTS	(
						SELECT *
						FROM PRS_SECURE_V.MDM_USER_PII AS PII
						WHERE PII.EMAIL_MAST_PREF_YN = 'N' AND A.DEMO_USER_ID = PII.USER_ID 
						AND user_slctd_id not in (
'mogucan',  --Gybasova, Kristina
'marieck_6',  --Eckert, Thomas
'sraudschus', --Peijan, Stefanie
'emnewman', --Newman, Emma
'mllewiwa', --(Kristin Wyrwa)
'the9280', -- (Theresa Thüs)
'sa-32439' , --(Sandy Kim)
'kathihartung832',
'marekmk', 
'dmalhao@ebay.com',
'psperling@ebay.de',  
'steffisoleil84')
						);

						


-- AUDIENCE CONTROL GROUP
UPDATE UNICA_TEMP.DE_FM_TARGETING_DAILY_EM_STG AS A
SET 
	EXCLUDE_REASON_CD = 99
WHERE
	EXCLUDE_REASON_CD IS NULL AND
	EXISTS	(
						SELECT *
						FROM UNICA_TEMP.DE_FAMILY_MEN_DAILY AS PII
						WHERE PII.TC = 'C' AND A.DEMO_USER_ID = PII.DEMO_USER_ID 
						);
					
						
--sel * from UNICA_TEMP.DE_FM_TARGETING_DAILY_EM_STG;						


/* PREPARING DATA FOR MC SENDOUT - 3rd */

DELETE FROM UNICA_TEMP.DE_FM_TARGETING_DAILY_MC ALL;

INSERT INTO UNICA_TEMP.DE_FM_TARGETING_DAILY_MC
--create multiset table UNICA_TEMP.DE_FM_TARGETING_DAILY_MC as (
SELECT
	STG.PRIMARY_USER_ID,
	STG.DEMO_USER_ID,
	STG.AUD_ID,
	AUD.AUD_NAME,
	STG.SEGM_ID,
	SEGM.SEGM_ABR AS SEGM_NAME,
	STG.JOURNEY_ID,
	STG.SEQUENCE,
	STG.HERO_MESSAGE,
	STG.MESSAGE2,
	NVL(STG.MESSAGE3,0) MESSAGE3,
	STG.MESSAGE4,
	STG.MESSAGE5,
	STG.MESSAGE6,
	DFMD.TC,
	CASE WHEN  CH_MC_YN =  'Y'	AND TC<>'C' then 'Y' else 'N' end as  CH_MC_YN,
	case when EXCLUDE_REASON_CD IS NULL OR EXCLUDE_REASON_CD = 99 THEN 'Y' else 'N' end as CH_EM_YN,	
	STG.DATA_DATE,
	STG.PLUS_POINTS,
	STG.REWARDS_DATE

FROM
	UNICA_TEMP.DE_FM_TARGETING_DAILY_EM_STG AS STG
		JOIN UNICA_TEMP.DE_FAMILY_MEN_DAILY AS DFMD
						ON  STG.DEMO_USER_ID = DFMD.DEMO_USER_ID
		INNER JOIN  UNICA_TEMP.XMP_AUDIENCE AS AUD
			ON 	STG.AUD_ID = AUD.AUD_ID AND
					CURRENT_DATE BETWEEN AUD.START_DATE-10 AND AUD.END_DATE
		
		INNER JOIN  UNICA_TEMP.XMP_SEGMENT AS SEGM
			ON 	STG.SEGM_ID = SEGM.SEGM_ID AND
					CURRENT_DATE BETWEEN SEGM.START_DATE-10 AND SEGM.END_DATE
		
		INNER JOIN PRS_SECURE_V.MDM_USER_PII AS PII
			ON STG.DEMO_USER_ID = PII.USER_ID

WHERE
	7=7
	AND CH_MC_YN='Y'
	AND TC='T'
	/*AND PII.user_slctd_id in (
'mogucan',  --Gybasova, Kristina
'marieck_6',  --Eckert, Thomas
'sraudschus', --Peijan, Stefanie
'dmalhao', --Malhao, Diogo
'marekmk', --Marek Mrazik
'emnewman', --Newman, Emma
'mllewiwa', --(Kristin Wyrwa)
'the9280', -- (Theresa Thüs)
'sa-32439' , --(Sandy Kim)
'kathihartung832')   --(Kathleen Hoffmann)
*/
;
/* PREPARING DATA FOR EMAIL SENDOUT */


DELETE FROM UNICA_TEMP.DE_FM_TARGETING_DAILY_EM ALL;

INSERT INTO UNICA_TEMP.DE_FM_TARGETING_DAILY_EM
SELECT
	STG.PRIMARY_USER_ID,
	STG.DEMO_USER_ID,
	STG.AUD_ID,
	AUD.AUD_NAME,
	STG.SEGM_ID,
	SEGM.SEGM_ABR AS SEGM_NAME,
	STG.JOURNEY_ID,
	STG.SEQUENCE,
	STG.HERO_MESSAGE,
	STG.MESSAGE2,
	STG.MESSAGE3,
	STG.MESSAGE4,
	STG.MESSAGE5,
	STG.MESSAGE6,
	PLUS_POINTS,
	REWARDS_DATE,
	CASE
		WHEN EXCLUDE_REASON_CD IS NULL THEN 'T'
		WHEN EXCLUDE_REASON_CD = 99 THEN 'C'
	END AS TC,
	STG.DATA_DATE

FROM
	UNICA_TEMP.DE_FM_TARGETING_DAILY_EM_STG AS STG
		
		INNER JOIN  UNICA_TEMP.XMP_AUDIENCE AS AUD
			ON 	STG.AUD_ID = AUD.AUD_ID AND
					CURRENT_DATE BETWEEN AUD.START_DATE-10 AND AUD.END_DATE
		
		INNER JOIN  UNICA_TEMP.XMP_SEGMENT AS SEGM
			ON 	STG.SEGM_ID = SEGM.SEGM_ID AND
					CURRENT_DATE BETWEEN SEGM.START_DATE-10 AND SEGM.END_DATE
		
		INNER JOIN PRS_SECURE_V.MDM_USER_PII AS PII
			ON STG.DEMO_USER_ID = PII.USER_ID

WHERE
	EXCLUDE_REASON_CD IS NULL 
	OR EXCLUDE_REASON_CD = 99
;

/* PREPARING DATA FOR DMP */
DELETE FROM UNICA_TEMP.DE_FM_TARGETING_DMP_NOPLUS_STG ALL;

INSERT INTO  UNICA_TEMP.DE_FM_TARGETING_DMP_NOPLUS_STG  
select  demo_user_id as user_id from UNICA_TEMP.DE_FAMILY_MEN_DAILY where TC='T'  --and ebay_plus= 'N'
;

/* PREPARING DATA FOR PN */
DELETE FROM UNICA_TEMP.DE_FM_TARGETING_DAILY_PN_STG ALL;

INSERT INTO  UNICA_TEMP.DE_FM_TARGETING_DAILY_PN_STG 
select  demo_user_id as user_id from UNICA_TEMP.DE_FAMILY_MEN_DAILY where TC='T'
;

--EM archiv
INSERT INTO  UNICA_TEMP.DE_FM_TARGETING_EM_ARCHIV 
SELECT * from UNICA_TEMP.DE_FM_TARGETING_DAILY_EM
;

--ALL archiv
INSERT INTO  UNICA_TEMP.DE_FM_TARGETING_ALL_ARCHIV 
SELECT * from UNICA_TEMP.DE_FM_TARGETING_DAILY_EM_STG a
;


/*
SELECT TC, HERO_MESSAGE,
	MESSAGE2,
	MESSAGE3,
	MESSAGE4,
	MESSAGE5,
	MESSAGE6,
	count(demo_user_id) FROM UNICA_TEMP.DE_FM_TARGETING_DAILY_EM
	group by 1,2,3,4,5,6,7;
	
	select  * from UNICA_TEMP.DE_FM_TARGETING_DAILY_EM  where rewards_date is not null
	
	
	sel TC, HERO_MESSAGE,
	MESSAGE2,
	MESSAGE3,
	MESSAGE4,
	MESSAGE5,
	MESSAGE6,
	count(a.demo_user_id)  from UNICA_TEMP.DE_FM_TARGETING_DAILY_EM_STG a	
	join  UNICA_TEMP.DE_FAMILY_MEN_DAILY b on a.demo_user_id=b.demo_user_id
	group by 1,2,3,4,5,6,7;
	
	
		sel TC, HERO_MESSAGE,
	MESSAGE2,
	MESSAGE3,
	MESSAGE4,
	MESSAGE5,
	MESSAGE6,
	count(a.demo_user_id)  from UNICA_TEMP.DE_FM_TARGETING_DAILY_MC a	
	
	group by 1,2,3,4,5,6,7;
	
	select exclude_reason_cd, count(demo_user_id) from UNICA_TEMP.DE_FM_TARGETING_DAILY_EM_STG  group by 1
	
	select exclude_reason_cd, count(demo_user_id) from UNICA_TEMP.DE_FAMILY_MEN_STG  group by 1
	
	*/
/*sel * from  P_DBM_INPUT_T.adobe_de_familymen_mam;
create multiset table   P_DBM_INPUT_T.adobe_de_familymen_mam as (
	SELECT demo_user_id as USER_ID, TC FROM UNICA_TEMP.DE_FAMILY_MEN_STG 
	) WITH DATA*/
	
	/*select coupon, TC,
	 EBAY_PLUS,
REWARDS_DATE,
MICROSEGMENT,	
	count(demo_user_id)
	from  UNICA_TEMP.DE_FAMILY_MEN_DAILY
	group by 1,2,3,4,5*/